'use client';

import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';

type SiteContent={id:number;display_name:string;short_name:string;headline:string;hero_text:string;role_title:string;location:string;email:string;phone:string;github_url:string;linkedin_url:string;portfolio_url:string;about_one:string;about_two:string;contact_heading:string;contact_text:string;experience_years:string;footer_text:string};
const defaults:SiteContent={id:1,display_name:'Kumar Vibhu',short_name:'Vibhu',headline:'I build modern, responsive and high-performance web products.',hero_text:'Full-Stack Developer focused on production-ready applications, APIs, automation and data-driven platforms — from interface to infrastructure.',role_title:'Full-Stack Developer',location:'India · Remote',email:'kumar.vibhu.id@gmail.com',phone:'+91 98163 99109',github_url:'https://github.com/vibhu10',linkedin_url:'',portfolio_url:'https://vibhu10.github.io/portfolio/',about_one:'I build production web applications and enjoy owning the complete engineering flow: translating requirements into interfaces, designing APIs and data models, integrating external services, automating repetitive work and shipping applications to the cloud.',about_two:'My strongest stack is JavaScript/TypeScript with React, Next.js and Node.js, plus Python/FastAPI, browser automation and modern databases when the product needs them.',contact_heading:'Let’s build something useful.',contact_text:'I’m open to full-stack, React/Next.js and product engineering opportunities.',experience_years:'3+',footer_text:'© 2026 Kumar Vibhu · Built with Next.js + Supabase'};

export default function ContentPanel({session}:{session:any}){
  const[data,setData]=useState<SiteContent>(defaults);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[err,setErr]=useState('');
  useEffect(()=>{load()},[]);
  const load=async()=>{if(!supabase)return;const{data:d,error}=await supabase.from('site_content').select('*').eq('id',1).maybeSingle();if(error){setErr(error.message);return}if(d)setData({...defaults,...d})};
  const set=(k:keyof SiteContent,v:any)=>setData(p=>({...p,[k]:v}));
  const save=async()=>{if(!supabase)return;setBusy(true);setErr('');setMsg('');const payload={...data,updated_at:new Date().toISOString()};const{error}=await supabase.from('site_content').upsert(payload,{onConflict:'id'});if(error)setErr(error.message);else{await supabase.from('activity_logs').insert({actor_user_id:session?.user?.id||null,action:'site_content_updated',entity_type:'site_content',entity_id:'1',details:{fields:Object.keys(payload)}});setMsg('Home page content saved. Changes are live immediately.')}setBusy(false)};
  return <div className="content-admin"><div className="content-head"><div><span className="admin-mark">HOME PAGE CMS</span><h2>Edit portfolio content</h2><p>Everything here powers the public home page, so you no longer need to edit code for your name, headline, contact information or About section.</p></div><button className="primary-btn" onClick={save} disabled={busy}>{busy?'Saving…':'Save all changes'}</button></div>{err&&<div className="error">{err}</div>}{msg&&<div className="notice">{msg}</div>}<div className="content-grid"><section className="admin-panel"><h3>Identity & hero</h3><label>Full name<input value={data.display_name} onChange={e=>set('display_name',e.target.value)}/></label><label>Short name<input value={data.short_name} onChange={e=>set('short_name',e.target.value)}/></label><label>Role title<input value={data.role_title} onChange={e=>set('role_title',e.target.value)}/></label><label>Main headline<textarea rows={3} value={data.headline} onChange={e=>set('headline',e.target.value)}/></label><label>Hero description<textarea rows={4} value={data.hero_text} onChange={e=>set('hero_text',e.target.value)}/></label><label>Location<input value={data.location} onChange={e=>set('location',e.target.value)}/></label><label>Experience label<input value={data.experience_years} onChange={e=>set('experience_years',e.target.value)} placeholder="3+"/></label></section><section className="admin-panel"><h3>Contact & links</h3><label>Email<input type="email" value={data.email} onChange={e=>set('email',e.target.value)}/></label><label>Phone<input value={data.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>GitHub URL<input value={data.github_url||''} onChange={e=>set('github_url',e.target.value)}/></label><label>LinkedIn URL<input value={data.linkedin_url||''} onChange={e=>set('linkedin_url',e.target.value)}/></label><label>Portfolio URL<input value={data.portfolio_url||''} onChange={e=>set('portfolio_url',e.target.value)}/></label><label>Contact heading<input value={data.contact_heading} onChange={e=>set('contact_heading',e.target.value)}/></label><label>Contact text<textarea rows={3} value={data.contact_text} onChange={e=>set('contact_text',e.target.value)}/></label></section><section className="admin-panel wide-content"><h3>About me</h3><label>About paragraph 1<textarea rows={5} value={data.about_one} onChange={e=>set('about_one',e.target.value)}/></label><label>About paragraph 2<textarea rows={5} value={data.about_two} onChange={e=>set('about_two',e.target.value)}/></label><label>Footer text<input value={data.footer_text} onChange={e=>set('footer_text',e.target.value)}/></label></section></div></div>
}
