'use client';

import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';

type Exp={id?:string;title:string;company:string;location:string;start_date:string;end_date:string;description:string;skills:string[];visible:boolean;sort_order:number};
const seed:Exp[]=[
{title:'Full-Stack Developer',company:'WebNext Technologies',location:'Mohali',start_date:'2024-02',end_date:'Present',description:'Building production applications, APIs, data pipelines, automation and cloud infrastructure, including Bird’s Eye Markets.',skills:['Next.js','Node.js','Python','Supabase','Docker'],visible:true,sort_order:0},
{title:'MERN Stack Developer',company:'ShineDezign',location:'Mohali',start_date:'2022-12',end_date:'2024-01',description:'Built full-stack product features, dashboards, authentication, APIs and data-heavy application experiences.',skills:['React','Node.js','Express.js','MongoDB'],visible:true,sort_order:1}
];
const empty:Exp={title:'',company:'',location:'',start_date:'',end_date:'',description:'',skills:[],visible:true,sort_order:0};

export default function ExperiencePanel({session}:{session:any}){
 const[items,setItems]=useState<Exp[]>([]),[editing,setEditing]=useState<Exp|null>(null),[busy,setBusy]=useState(false),[err,setErr]=useState(''),[msg,setMsg]=useState('');
 useEffect(()=>{bootstrap()},[]);
 const load=async()=>{if(!supabase)return;const{data,error}=await supabase.from('experiences').select('*').order('sort_order');if(error)setErr(error.message);else setItems(data||[])};
 const bootstrap=async()=>{if(!supabase)return;setBusy(true);const{data,error}=await supabase.from('experiences').select('title,company');if(error){setErr(error.message);setBusy(false);return}const keys=new Set((data||[]).map((x:any)=>`${x.title}|${x.company}`.toLowerCase()));const missing=seed.filter(x=>!keys.has(`${x.title}|${x.company}`.toLowerCase()));if(missing.length)await supabase.from('experiences').insert(missing);await load();setBusy(false)};
 const log=async(action:string,id:string,details:any)=>{if(!supabase)return;await supabase.from('activity_logs').insert({actor_user_id:session?.user?.id||null,action,entity_type:'experience',entity_id:id,details})};
 const save=async()=>{if(!supabase||!editing)return;setBusy(true);setErr('');const payload={...editing,updated_at:new Date().toISOString()};delete (payload as any).id;let id=editing.id||'';if(editing.id){const{error}=await supabase.from('experiences').update(payload).eq('id',editing.id);if(error){setErr(error.message);setBusy(false);return}}else{const{data,error}=await supabase.from('experiences').insert(payload).select('id').single();if(error){setErr(error.message);setBusy(false);return}id=data.id}await log(editing.id?'experience_updated':'experience_created',id,{title:editing.title,company:editing.company});setEditing(null);setMsg('Experience saved.');await load();setBusy(false)};
 const remove=async(x:Exp)=>{if(!supabase||!x.id||!confirm(`Delete ${x.title} at ${x.company}?`))return;await supabase.from('experiences').delete().eq('id',x.id);await log('experience_deleted',x.id,{title:x.title,company:x.company});load()};
 const toggle=async(x:Exp)=>{if(!supabase||!x.id)return;await supabase.from('experiences').update({visible:!x.visible}).eq('id',x.id);load()};
 return <div className="cms-panel">{err&&<div className="error">{err}</div>}{msg&&<div className="notice">{msg}</div>}<div className="cms-head"><div><span className="admin-mark">EXPERIENCE CMS</span><h2>Career experience</h2><p>Add, edit, hide or remove positions shown on your public portfolio.</p></div><button className="primary-btn" onClick={()=>setEditing({...empty,sort_order:items.length})}>+ Add experience</button></div><div className="experience-list">{items.map(x=><article className="experience-admin-card" key={x.id}><div className="experience-dot"/><div className="experience-main"><div className="row-title"><div><h3>{x.title}</h3><small>{x.company}{x.location?` · ${x.location}`:''}</small></div><span className={x.visible?'published':'hidden'}>{x.visible?'LIVE':'HIDDEN'}</span></div><b>{x.start_date} — {x.end_date}</b><p>{x.description}</p><div className="mini-tags">{(x.skills||[]).map(s=><span key={s}>{s}</span>)}</div><div className="card-actions"><button onClick={()=>setEditing({...x})}>✎ Edit</button><button onClick={()=>toggle(x)}>{x.visible?'Hide':'Publish'}</button><button className="danger" onClick={()=>remove(x)}>Delete</button></div></div></article>)}</div>{editing&&<div className="modal-backdrop"><div className="project-modal"><div className="modal-head"><div><span className="admin-mark">EXPERIENCE EDITOR</span><h2>{editing.id?'Edit experience':'Add experience'}</h2></div><button onClick={()=>setEditing(null)}>×</button></div><div className="form-grid"><label>Job title<input value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label>Company<input value={editing.company} onChange={e=>setEditing({...editing,company:e.target.value})}/></label><label>Location<input value={editing.location} onChange={e=>setEditing({...editing,location:e.target.value})}/></label><label>Start date<input placeholder="2024-02" value={editing.start_date} onChange={e=>setEditing({...editing,start_date:e.target.value})}/></label><label>End date<input placeholder="Present" value={editing.end_date} onChange={e=>setEditing({...editing,end_date:e.target.value})}/></label><label className="wide">Description<textarea rows={5} value={editing.description} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label className="wide">Skills <span className="hint">comma separated</span><input value={(editing.skills||[]).join(', ')} onChange={e=>setEditing({...editing,skills:e.target.value.split(',').map(v=>v.trim()).filter(Boolean)})}/></label></div><div className="checks"><label><input type="checkbox" checked={editing.visible} onChange={e=>setEditing({...editing,visible:e.target.checked})}/> Show publicly</label></div><div className="modal-actions"><button className="ghost-btn" onClick={()=>setEditing(null)}>Cancel</button><button className="primary-btn" onClick={save} disabled={busy}>{busy?'Saving…':'Save experience'}</button></div></div></div>}</div>
}
