'use client';

import {useEffect,useState} from 'react';
import {supabase,isSupabaseConfigured} from '../../lib/supabase';

type Props={session:any;resumeUrl:string};
type Settings={public_chat:boolean;recruiter_mode:boolean;include_projects:boolean;include_experience:boolean;include_skills:boolean;require_job_approval:boolean;auto_sync_knowledge:boolean};
const defaults:Settings={public_chat:true,recruiter_mode:true,include_projects:true,include_experience:true,include_skills:true,require_job_approval:true,auto_sync_knowledge:true};

export default function JarvisPanel({session,resumeUrl}:Props){
 const[settings,setSettings]=useState<Settings>(defaults),[command,setCommand]=useState(''),[reply,setReply]=useState('Jarvis admin systems ready.'),[busy,setBusy]=useState(false),[githubStatus,setGithubStatus]=useState('Not checked');
 useEffect(()=>{try{const raw=localStorage.getItem('jarvis_admin_settings');if(raw)setSettings({...defaults,...JSON.parse(raw)})}catch{}},[]);
 const save=(next:Settings)=>{setSettings(next);try{localStorage.setItem('jarvis_admin_settings',JSON.stringify(next))}catch{}};
 const toggle=(k:keyof Settings)=>save({...settings,[k]:!settings[k]});
 const ask=async()=>{const q=command.trim();if(!q)return;setBusy(true);let answer='';try{if(supabase&&isSupabaseConfigured){const[s,p,k,e]=await Promise.all([supabase.from('site_content').select('*').eq('id',1).maybeSingle(),supabase.from('projects').select('*').order('sort_order'),supabase.from('skills').select('*').order('sort_order'),supabase.from('experiences').select('*').order('sort_order')]);const{data,error}=await supabase.functions.invoke('jarvis',{body:{mode:'admin',message:q,context:{site:s.data,projects:p.data,skills:k.data,experiences:e.data},user_id:session?.user?.id}});if(!error&&data?.answer)answer=data.answer}}catch{}
  if(!answer){const l=q.toLowerCase();if(l.includes('resume'))answer='Resume workflow ready: review the current PDF, then use the portfolio Projects/Experience panels as the source of truth. Secure AI generation becomes available when the Jarvis Edge Function is deployed.';else if(l.includes('project'))answer='Project data is managed in the Projects panel. Jarvis will use all visible project summaries, impact, roles and technologies as knowledge.';else if(l.includes('job')||l.includes('apply'))answer='Job automation is configured for approval-first mode. Jarvis should prepare and prefill an application, but it must ask you before any final submission.';else answer='I can help manage portfolio knowledge, resume updates, project summaries, GitHub checks and job-application preparation. The generative AI layer activates through the secure Jarvis Edge Function.'}setReply(answer);setCommand('');setBusy(false)};
 const checkGithub=async()=>{setGithubStatus('Checking…');try{const r=await fetch('https://api.github.com/repos/vibhu10/portfolio');if(!r.ok)throw new Error();const d=await r.json();setGithubStatus(`Connected · ${d.stargazers_count??0} stars · updated ${new Date(d.updated_at).toLocaleDateString()}`)}catch{setGithubStatus('Could not reach GitHub from this browser')}};
 const integration=(name:string,status:string,detail:string,action?:()=>void)=><article className='jarvis-integration'><div><b>{name}</b><small>{detail}</small></div><span className={status.startsWith('Connected')?'connected':''}>{status}</span>{action&&<button onClick={action}>Check</button>}</article>;
 return <div className='jarvis-admin'><section className='jarvis-console'><div className='jarvis-console-head'><div className='jarvis-admin-orb'>J</div><div><span className='admin-mark'>JARVIS · AI OPERATIONS</span><h2>Portfolio command center</h2><p>One assistant for recruiter chat, portfolio knowledge, resume workflows and approved third-party actions.</p></div><em>MARK I</em></div><div className='jarvis-terminal'><span>COMMAND</span><div><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder='e.g. Prepare my resume for a senior full-stack role'/><button onClick={ask} disabled={busy}>{busy?'Running…':'Run →'}</button></div><pre>{reply}</pre></div></section>
 <div className='jarvis-admin-grid'><section className='admin-panel'><span className='admin-mark'>BEHAVIOR</span><h2>Jarvis settings</h2>{(Object.keys(settings) as (keyof Settings)[]).map(k=><label className='jarvis-toggle' key={k}><span><b>{k.replaceAll('_',' ')}</b><small>{k==='require_job_approval'?'Recommended: Jarvis prepares applications but never submits without your approval.':'Controls what Jarvis can use or show.'}</small></span><input type='checkbox' checked={settings[k]} onChange={()=>toggle(k)}/></label>)}</section>
 <section className='admin-panel'><span className='admin-mark'>KNOWLEDGE</span><h2>Resume & portfolio brain</h2><p>Jarvis reads your live Projects, Experience, Skills and Home Content from Supabase. Keep those sections accurate and Jarvis stays accurate.</p><a className='asset-link' href={resumeUrl} target='_blank'>Open current resume ↗</a><div className='jarvis-note'><b>Resume updating</b><p>Jarvis can draft updated resume content from new projects. Replacing the final PDF remains an explicit admin action so it cannot silently change your job document.</p></div></section>
 <section className='admin-panel jarvis-integrations'><span className='admin-mark'>INTEGRATIONS</span><h2>Apps & job channels</h2>{integration('GitHub',githubStatus,'Repository/project activity sync',checkGithub)}{integration('LinkedIn','OAuth required','Profile/job actions require LinkedIn-supported authorization.')}{integration('Job portals','Connector required','Each portal needs its own supported API/OAuth or browser workflow.')}{integration('OpenAI','Edge Function','API key stays server-side in Supabase — never in this website.')}</section>
 <section className='admin-panel'><span className='admin-mark'>JOB AGENT</span><h2>Application workflow</h2><ol className='jarvis-flow'><li>Find or import a job</li><li>Compare requirements with your portfolio</li><li>Prepare tailored resume/profile answers</li><li>Show application preview</li><li><b>You approve final submission</b></li></ol><p className='jarvis-warning'>Jarvis will not claim skills you have not added and will not silently submit applications when approval mode is enabled.</p></section></div><style>{`
.jarvis-admin{display:grid;gap:18px}.jarvis-console{border:1px solid #1e4658;background:radial-gradient(circle at 90% 0,rgba(39,181,224,.11),transparent 32%),linear-gradient(145deg,#08131b,#071016);border-radius:18px;overflow:hidden}.jarvis-console-head{display:flex;align-items:center;gap:18px;padding:22px;border-bottom:1px solid #17313f}.jarvis-admin-orb{width:60px;height:60px;border-radius:50%;display:grid;place-items:center;border:1px solid #3ccaf2;color:#d8f7ff;font-size:22px;font-weight:900;background:radial-gradient(circle,#25627c,#07121a 67%);box-shadow:0 0 32px rgba(57,205,246,.18)}.jarvis-console-head>div:nth-child(2){flex:1}.jarvis-console-head h2{margin:4px 0 3px}.jarvis-console-head p{margin:0;color:#78909c;font-size:12px}.jarvis-console-head em{font:800 9px ui-monospace,monospace;color:#56c8e9;border:1px solid #1e5365;padding:6px 9px;border-radius:999px}.jarvis-terminal{padding:18px 22px}.jarvis-terminal>span{font:800 9px ui-monospace,monospace;letter-spacing:1px;color:#4f9bb4}.jarvis-terminal>div{display:flex;gap:8px;margin-top:7px}.jarvis-terminal input{flex:1;background:#050c11;color:#d9edf4;border:1px solid #1c3a47;border-radius:9px;padding:12px}.jarvis-terminal button{border:0;border-radius:9px;padding:0 16px;background:#41c8ee;color:#051017;font-weight:800}.jarvis-terminal pre{white-space:pre-wrap;margin:13px 0 0;padding:12px;border-radius:9px;background:#050b10;color:#8fb4c2;font:11px/1.6 ui-monospace,monospace}.jarvis-admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.jarvis-toggle{display:flex;justify-content:space-between;gap:20px;padding:13px 0;border-top:1px solid #252b36}.jarvis-toggle span{display:flex;flex-direction:column}.jarvis-toggle b{text-transform:capitalize;font-size:12px}.jarvis-toggle small{color:#78808c;font-size:10px;margin-top:3px}.jarvis-toggle input{accent-color:#3cccf2}.jarvis-note{margin-top:16px;padding:13px;border:1px solid #273341;border-radius:10px;background:#0d141c}.jarvis-note p{margin:5px 0 0;font-size:11px;color:#818b97}.jarvis-integrations{display:grid;gap:8px}.jarvis-integration{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:10px;border:1px solid #29303a;border-radius:10px;padding:11px}.jarvis-integration div{display:flex;flex-direction:column}.jarvis-integration small{color:#767f8a;font-size:9px;margin-top:2px}.jarvis-integration span{font-size:9px;color:#ddaa62}.jarvis-integration span.connected{color:#5dd4a7}.jarvis-integration button{background:#151d25;color:#cfe7f0;border:1px solid #344653;border-radius:7px;padding:6px 8px;font-size:9px}.jarvis-flow{padding-left:20px;color:#a6aeba;font-size:12px;line-height:2}.jarvis-warning{font-size:10px!important;color:#ba9567!important;border-top:1px solid #302b25;padding-top:11px}@media(max-width:900px){.jarvis-admin-grid{grid-template-columns:1fr}}`}</style></div>
}
