'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../../lib/supabase';

type Msg={id:string;name:string;email:string;subject:string;message:string;status:'unread'|'read'|'archived';created_at:string};

export default function MessagesPanel({onUnreadChange}:{onUnreadChange?:(n:number)=>void}){
 const[items,setItems]=useState<Msg[]>([]),[selected,setSelected]=useState<Msg|null>(null),[filter,setFilter]=useState('all'),[err,setErr]=useState('');
 useEffect(()=>{load();if(!supabase)return;const ch=supabase.channel('portfolio-message-inbox').on('postgres_changes',{event:'INSERT',schema:'public',table:'contact_messages'},()=>load()).subscribe();return()=>{supabase.removeChannel(ch)}},[]);
 const load=async()=>{if(!supabase)return;const{data,error}=await supabase.from('contact_messages').select('*').order('created_at',{ascending:false});if(error)setErr(error.message);else{const rows=(data||[]) as Msg[];setItems(rows);onUnreadChange?.(rows.filter(x=>x.status==='unread').length)}};
 const unread=useMemo(()=>items.filter(x=>x.status==='unread').length,[items]);
 const shown=filter==='all'?items:items.filter(x=>x.status===filter);
 const open=async(m:Msg)=>{setSelected(m);if(m.status==='unread'&&supabase){await supabase.from('contact_messages').update({status:'read',read_at:new Date().toISOString()}).eq('id',m.id);load()}};
 const change=async(m:Msg,status:'unread'|'read'|'archived')=>{if(!supabase)return;await supabase.from('contact_messages').update({status,read_at:status==='read'?new Date().toISOString():null}).eq('id',m.id);setSelected(null);load()};
 const remove=async(m:Msg)=>{if(!supabase||!confirm(`Delete message from ${m.name}?`))return;await supabase.from('contact_messages').delete().eq('id',m.id);setSelected(null);load()};
 return <div className="cms-panel">{err&&<div className="error">{err}</div>}<div className="cms-head"><div><span className="admin-mark">PORTFOLIO INBOX</span><h2>Messages <span className="count-badge">{unread} unread</span></h2><p>Messages sent through your public portfolio appear here automatically.</p></div><button className="secondary-btn" onClick={load}>Refresh inbox</button></div><div className="inbox-layout"><aside className="inbox-filters">{['all','unread','read','archived'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x[0].toUpperCase()+x.slice(1)} <span>{x==='all'?items.length:items.filter(i=>i.status===x).length}</span></button>)}</aside><section className="inbox-list">{shown.length?shown.map(m=><button className={'message-row '+(m.status==='unread'?'unread':'')} onClick={()=>open(m)} key={m.id}><span className="message-avatar">{m.name.slice(0,1).toUpperCase()}</span><span className="message-copy"><b>{m.name}</b><small>{m.email}</small><strong>{m.subject||'Portfolio enquiry'}</strong><p>{m.message}</p></span><time>{new Date(m.created_at).toLocaleString()}</time></button>):<div className="empty">No messages in this view.</div>}</section></div>{selected&&<div className="modal-backdrop"><div className="message-modal"><div className="modal-head"><div><span className="admin-mark">MESSAGE</span><h2>{selected.subject||'Portfolio enquiry'}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><div className="sender-card"><div className="message-avatar large">{selected.name.slice(0,1).toUpperCase()}</div><div><b>{selected.name}</b><a href={`mailto:${selected.email}`}>{selected.email}</a><small>{new Date(selected.created_at).toLocaleString()}</small></div></div><div className="message-body">{selected.message}</div><div className="message-actions"><a className="primary-btn" href={`mailto:${selected.email}?subject=Re: ${encodeURIComponent(selected.subject||'Your portfolio message')}`}>Reply by email ↗</a><button onClick={()=>change(selected,'unread')}>Mark unread</button><button onClick={()=>change(selected,'archived')}>Archive</button><button className="danger" onClick={()=>remove(selected)}>Delete</button></div></div></div>}</div>
}
