'use client';

import {useMemo} from 'react';

type Event={id:string;visitor_id:string;event_type:string;page:string;referrer:string|null;user_agent:string|null;language:string|null;timezone:string|null;created_at:string};
type Project={id?:string;name:string;category:string;summary:string;impact:string;role:string[];tech:string[];screenshots:string[];live_url:string;github_url:string;featured:boolean;visible:boolean;sort_order:number};
type Skill={id?:string;category:string;name:string;sort_order:number;visible:boolean};

export default function ModernDashboard({events,projects,skills,health,onTest}:{events:Event[];projects:Project[];skills:Skill[];health:Record<string,string>;onTest:()=>void}){
  const uniqueVisitors=useMemo(()=>new Set(events.map(e=>e.visitor_id)).size,[events]);
  const views=events.filter(e=>e.event_type==='page_view').length;
  const resumeClicks=events.filter(e=>e.event_type==='resume_download').length;
  const contactClicks=events.filter(e=>e.event_type==='contact_click').length;
  const days=useMemo(()=>{const out:{label:string;views:number;visitors:Set<string>}[]=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);out.push({label:d.toLocaleDateString(undefined,{weekday:'short'}),views:0,visitors:new Set()})}events.forEach(e=>{const d=new Date(e.created_at);const diff=Math.floor((new Date().setHours(0,0,0,0)-new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime())/86400000);if(diff>=0&&diff<7){const x=out[6-diff];if(e.event_type==='page_view')x.views++;x.visitors.add(e.visitor_id)}});return out},[events]);
  const max=Math.max(1,...days.map(d=>d.views));
  const eventBreakdown=useMemo(()=>{const map:Record<string,number>={};events.forEach(e=>map[e.event_type]=(map[e.event_type]||0)+1);return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,5)},[events]);
  const topPages=useMemo(()=>{const map:Record<string,number>={};events.filter(e=>e.event_type==='page_view').forEach(e=>map[e.page]=(map[e.page]||0)+1);return Object.entries(map).sort((a,b)=>b[1]-a[1]).slice(0,5)},[events]);
  const connected=Object.values(health).filter(v=>v.startsWith('Connected')).length,totalHealth=Math.max(1,Object.keys(health).length);
  return <div className="modern-dashboard">
    <section className="overview-strip"><div><span className="eyebrow">LIVE PORTFOLIO INTELLIGENCE</span><h2>Performance at a glance</h2><p>Traffic, engagement, content and system status in one place.</p></div><div className="health-score"><div className="health-ring" style={{'--score':`${(connected/totalHealth)*360}deg`} as any}><strong>{Math.round((connected/totalHealth)*100)}%</strong></div><span>System health</span></div></section>
    <section className="metric-grid modern-metrics"><Metric icon="◎" label="Unique visitors" value={uniqueVisitors} meta="Audience reach"/><Metric icon="↗" label="Page views" value={views} meta="Total browsing activity"/><Metric icon="⇩" label="Resume clicks" value={resumeClicks} meta="Recruiter intent"/><Metric icon="✉" label="Contact clicks" value={contactClicks} meta="Direct engagement"/></section>
    <section className="dashboard-analytics-grid"><div className="admin-panel chart-card"><div className="panel-head"><div><span className="eyebrow">LAST 7 DAYS</span><h2>Traffic trend</h2><p>Daily page views and unique visitors.</p></div></div><div className="bar-chart">{days.map((d,i)=><div className="bar-col" key={d.label+i}><div className="bar-values"><span>{d.views}</span><small>{d.visitors.size} users</small></div><div className="bar-track"><div className="bar-fill" style={{height:`${Math.max(8,(d.views/max)*100)}%`}}/></div><label>{d.label}</label></div>)}</div></div>
      <div className="admin-panel engagement-card"><div className="panel-head"><div><span className="eyebrow">ENGAGEMENT MIX</span><h2>Actions</h2><p>What visitors are doing.</p></div></div><div className="event-bars">{eventBreakdown.length?eventBreakdown.map(([name,count])=><div key={name}><div><span>{name.replaceAll('_',' ')}</span><strong>{count}</strong></div><div className="mini-track"><i style={{width:`${Math.max(8,(count/Math.max(1,eventBreakdown[0][1]))*100)}%`}}/></div></div>):<p className="empty-note">No activity yet.</p>}</div></div>
    </section>
    <section className="dashboard-lower-grid"><div className="admin-panel"><div className="panel-head"><div><span className="eyebrow">CONTENT</span><h2>Portfolio inventory</h2><p>Live content currently managed in Supabase.</p></div></div><div className="inventory-grid"><Inventory value={projects.length} label="Projects"/><Inventory value={projects.filter(p=>p.visible).length} label="Published"/><Inventory value={projects.filter(p=>p.featured).length} label="Featured"/><Inventory value={skills.length} label="Skills"/></div><div className="top-pages"><h3>Top pages</h3>{topPages.length?topPages.map(([page,count])=><div key={page}><span>{page}</span><strong>{count}</strong></div>):<div className="empty-note">No page-view data yet.</div>}</div></div>
      <div className="admin-panel system-card"><div className="panel-head"><div><span className="eyebrow">INFRASTRUCTURE</span><h2>Supabase health</h2><p>Database, analytics and storage status.</p></div></div>{Object.entries(health).map(([k,v])=><div className={'health-row '+(v.startsWith('Connected')?'ok':'bad')} key={k}><div><i/><b>{k}</b></div><span>{v}</span></div>)}<button className="secondary-btn full-btn" onClick={onTest}>Run analytics write test</button></div></section>
    <section className="admin-panel recent-card"><div className="panel-head"><div><span className="eyebrow">RECENT ACTIVITY</span><h2>Latest visitors</h2><p>Anonymous browser IDs only; no raw IP is stored.</p></div></div><div className="recent-visitors">{events.slice(0,8).map(e=><div key={e.id}><span className="event-dot"/><div><strong>{e.event_type.replaceAll('_',' ')}</strong><small>{e.page} · {new Date(e.created_at).toLocaleString()}</small></div><code>{e.visitor_id.slice(0,10)}…</code></div>)}</div></section>
  </div>
}
function Metric({icon,label,value,meta}:{icon:string;label:string;value:number;meta:string}){return <div className="metric modern-metric"><div className="metric-icon">{icon}</div><div><small>{label}</small><strong>{value}</strong><span>{meta}</span></div></div>}
function Inventory({value,label}:{value:number;label:string}){return <div><strong>{value}</strong><span>{label}</span></div>}
