'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,isSupabaseConfigured} from '../../lib/supabase';
import TeamPanel from './TeamPanel';
import ModernDashboard from './ModernDashboard';
import ContentPanel from './ContentPanel';
import ProjectPanel from './ProjectPanel';
import ExperiencePanel from './ExperiencePanel';
import MessagesPanel from './MessagesPanel';
import SkillPanel from './SkillPanel';
import './admin.css';
import './modern-dashboard.css';
import './team/team.css';

type Project={id?:string;name:string;category:string;summary:string;impact:string;role:string[];tech:string[];screenshots:string[];live_url:string;github_url:string;featured:boolean;visible:boolean;sort_order:number};
type Skill={id?:string;category:string;name:string;sort_order:number;visible:boolean};
type Event={id:string;visitor_id:string;event_type:string;page:string;referrer:string|null;user_agent:string|null;language:string|null;timezone:string|null;created_at:string};
type UserProfile={full_name:string;email:string;avatar_url:string|null;role:string;status?:string;permissions:Record<string,boolean>};
const BASE='/portfolio';

export default function Admin(){
  const[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('dashboard'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[projects,setProjects]=useState<Project[]>([]),[skills,setSkills]=useState<Skill[]>([]),[events,setEvents]=useState<Event[]>([]),[profileUrl,setProfileUrl]=useState(`${BASE}/profile-320.jpg`),[resumeUrl,setResumeUrl]=useState(`${BASE}/resume.pdf`),[health,setHealth]=useState<Record<string,string>>({}),[unread,setUnread]=useState(0),[currentUser,setCurrentUser]=useState<UserProfile|null>(null);
  const configured=isSupabaseConfigured&&!!supabase;
  useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
  useEffect(()=>{if(session){loadAll();loadUnread();loadCurrentUser()}else setCurrentUser(null)},[session]);

  const logAction=async(action:string,entityType:string,entityId:string,details:any={})=>{if(!supabase||!session?.user?.id)return;await supabase.from('activity_logs').insert({actor_user_id:session.user.id,action,entity_type:entityType,entity_id:entityId,details})};
  const playManagerLoginSound=()=>{if(typeof window==='undefined'||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance('Jhuk ke rehna hoga');voice.lang='hi-IN';voice.rate=.9;voice.pitch=.85;voice.volume=1;window.speechSynthesis.speak(voice)};
  const loadCurrentUser=async()=>{if(!supabase||!session?.user)return;const{data}=await supabase.from('profiles').select('full_name,email,avatar_url,role,status,permissions').eq('user_id',session.user.id).maybeSingle();setCurrentUser(data?{full_name:data.full_name||session.user.user_metadata?.full_name||session.user.email||'User',email:data.email||session.user.email||'',avatar_url:data.avatar_url||null,role:data.role||'viewer',status:data.status,permissions:data.permissions||{}}:{full_name:session.user.user_metadata?.full_name||session.user.email||'User',email:session.user.email||'',avatar_url:null,role:'viewer',permissions:{}})};
  const loadUnread=async()=>{if(!supabase)return;const{count,error}=await supabase.from('contact_messages').select('*',{count:'exact',head:true}).eq('status','unread');if(!error)setUnread(count||0)};
  const loadAll=async()=>{if(!supabase)return;setError('');const[p,s,e,a]=await Promise.all([supabase.from('projects').select('*').order('sort_order'),supabase.from('skills').select('*').order('sort_order'),supabase.from('visitor_events').select('*').order('created_at',{ascending:false}).limit(500),supabase.storage.from('portfolio').list('site')]);const h:Record<string,string>={};if(p.error)h.projects=p.error.message;else{setProjects(p.data||[]);h.projects=`Connected · ${p.data?.length||0} records`}if(s.error)h.skills=s.error.message;else{setSkills(s.data||[]);h.skills=`Connected · ${s.data?.length||0} records`}if(e.error)h.analytics=e.error.message;else{setEvents(e.data||[]);h.analytics=`Connected · ${e.data?.length||0} events`}if(a.error)h.storage=a.error.message;else{h.storage='Connected';const names=new Set((a.data||[]).map(x=>x.name));if(names.has('profile.jpg'))setProfileUrl(supabase.storage.from('portfolio').getPublicUrl('site/profile.jpg').data.publicUrl);if(names.has('resume.pdf'))setResumeUrl(supabase.storage.from('portfolio').getPublicUrl('site/resume.pdf').data.publicUrl)}setHealth(h)};
  const login=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!supabase){setError('Supabase is not configured yet.');return}const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error){setError(error.message);return}if(data.user){const{data:profile}=await supabase.from('profiles').select('full_name,email,avatar_url,role,status,permissions').eq('user_id',data.user.id).maybeSingle();if(profile?.status==='suspended'){await supabase.auth.signOut();setError('Your account is suspended. Contact the portfolio owner.');return}if(profile)setCurrentUser({full_name:profile.full_name||data.user.email||'User',email:profile.email||data.user.email||'',avatar_url:profile.avatar_url||null,role:profile.role||'viewer',status:profile.status,permissions:profile.permissions||{}});await supabase.from('profiles').update({last_login_at:new Date().toISOString()}).eq('user_id',data.user.id);await supabase.from('activity_logs').insert({actor_user_id:data.user.id,action:'login',entity_type:'session',entity_id:data.user.id,details:{role:profile?.role||'unassigned',email:data.user.email}});if(profile?.role==='manager')playManagerLoginSound()}};
  const logout=async()=>{await logAction('logout','session',session?.user?.id||'',{});await supabase?.auth.signOut()};
  const uploadSiteAsset=async(kind:'profile'|'resume',file:File|null)=>{if(!supabase||!file)return;if(kind==='profile'&&!file.type.startsWith('image/'))return setError('Profile photo must be an image.');if(kind==='resume'&&file.type!=='application/pdf')return setError('Resume must be a PDF.');const path=kind==='profile'?'site/profile.jpg':'site/resume.pdf';const{error}=await supabase.storage.from('portfolio').upload(path,file,{contentType:file.type,upsert:true,cacheControl:'60'});if(error)return setError(error.message);const url=supabase.storage.from('portfolio').getPublicUrl(path).data.publicUrl;if(kind==='profile')setProfileUrl(`${url}?v=${Date.now()}`);else setResumeUrl(`${url}?v=${Date.now()}`);await logAction(kind==='profile'?'profile_photo_updated':'resume_updated','storage',path,{name:file.name,size:file.size});setNotice(`${kind==='profile'?'Profile photo':'Resume'} updated.`);await loadAll()};
  const testAnalytics=async()=>{if(!supabase)return;const{error}=await supabase.from('visitor_events').insert({visitor_id:`admin-test-${Date.now()}`,event_type:'admin_test',page:'/admin',referrer:null,user_agent:navigator.userAgent,language:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});if(error)setError(error.message);else{await logAction('analytics_test','analytics','admin_test',{});setNotice('Analytics test succeeded.');loadAll()}};
  const uniqueVisitors=useMemo(()=>new Set(events.map(e=>e.visitor_id)).size,[events]),views=events.filter(e=>e.event_type==='page_view').length,resumeClicks=events.filter(e=>e.event_type==='resume_download').length,contactClicks=events.filter(e=>e.event_type==='contact_click').length;

  if(loading)return <div className="admin-loading">Loading admin…</div>;
  if(!configured)return <main className="admin-shell"><div className="setup-card"><span className="admin-mark">ADMIN SETUP</span><h1>Connect your portfolio CMS.</h1><p>Add your Supabase URL and anon key to GitHub Actions secrets, deploy again, then run the latest Supabase migration.</p></div></main>;
  if(!session)return <main className="admin-shell"><form className="login-card" onSubmit={login}><span className="admin-mark">PRIVATE · PORTFOLIO ADMIN</span><h1>Welcome back.</h1><p>Manage your complete portfolio, team, inbox and analytics.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<div className="login-password-wrap"><input type={showPassword?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Hide password':'Show password'}>{showPassword?'🙈':'👁'}</button></div></label><a className="login-forgot" href={`${BASE}/forgot-password/`}>Forgot password?</a>{error&&<div className="error">{error}</div>}<button className="admin-btn primary-btn">Sign in ↗</button><a className="login-request" href={`${BASE}/access-request/`}>Need access? Request an account →</a></form></main>;

  const canManageTeam=!!currentUser&&(currentUser.role==='owner'||currentUser.role==='admin'||!!currentUser.permissions?.manage_users||!!currentUser.permissions?.approve_users||!!currentUser.permissions?.assign_roles);
  const baseMenu=[['dashboard','◈ Dashboard'],['content','✎ Home Content'],['projects','▣ Projects'],['experience','▤ Experience'],['skills','✦ Skills'],['analytics','⌁ Analytics'],['messages','✉ Messages'],['settings','⚙ Settings']];
  const menu=canManageTeam?[...baseMenu.slice(0,7),['team','♟ Team & Access'],...baseMenu.slice(7)]:baseMenu;
  const title=tab==='team'?'Dashboard':tab==='content'?'Home Content':tab[0].toUpperCase()+tab.slice(1);
  const initials=(currentUser?.full_name||session?.user?.email||'U').split(/\s+/).filter(Boolean).slice(0,2).map((x:string)=>x[0]?.toUpperCase()).join('');
  const effectiveTab=tab==='team'&&!canManageTeam?'dashboard':tab;
  return <main className="admin-app"><aside><a href={`${BASE}/`} className="admin-brand">VIBHU<span>ADMIN</span></a>{menu.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={effectiveTab===k?'active':''}><span>{l}</span>{k==='messages'&&unread>0&&<b className="nav-badge">{unread}</b>}</button>)}<div className="side-bottom"><button onClick={logout}>↪ Sign out</button></div></aside><section className="admin-main"><header className="admin-top"><div><span className="admin-mark">PORTFOLIO CONTROL CENTER</span><h1>{effectiveTab==='team'?'Team & Access':effectiveTab==='content'?'Home Content':effectiveTab[0].toUpperCase()+effectiveTab.slice(1)}</h1></div><div className="admin-top-right"><div className="signed-user">{currentUser?.avatar_url?<img src={currentUser.avatar_url} alt={currentUser.full_name}/>:<span className="signed-user-avatar">{initials}</span>}<div><strong>{currentUser?.full_name||session?.user?.user_metadata?.full_name||session?.user?.email}</strong><small>{currentUser?.role||'user'}</small></div></div><div className="admin-actions"><button onClick={()=>{loadAll();loadUnread();loadCurrentUser()}}>Refresh</button><a href={`${BASE}/`} target="_blank">View live site ↗</a></div></div></header>{error&&<div className="error global-error">{error}</div>}{notice&&<div className="notice global-error">{notice}</div>}
  {effectiveTab==='dashboard'&&<ModernDashboard events={events} projects={projects} skills={skills} health={health} onTest={testAnalytics}/>} 
  {effectiveTab==='content'&&<ContentPanel session={session}/>} 
  {effectiveTab==='projects'&&<ProjectPanel session={session}/>} 
  {effectiveTab==='experience'&&<ExperiencePanel session={session}/>} 
  {effectiveTab==='skills'&&<SkillPanel session={session}/>} 
  {effectiveTab==='analytics'&&<div className="admin-panel"><div className="panel-head"><div><h2>Visitor analytics</h2><p>Portfolio views and important actions.</p></div></div><div className="metric-grid"><Metric label="Unique visitors" value={uniqueVisitors}/><Metric label="Page views" value={views}/><Metric label="Resume clicks" value={resumeClicks}/><Metric label="Contact clicks" value={contactClicks}/></div><VisitorTable events={events}/></div>}
  {effectiveTab==='messages'&&<MessagesPanel onUnreadChange={setUnread}/>} 
  {effectiveTab==='team'&&canManageTeam&&<TeamPanel session={session}/>} 
  {effectiveTab==='settings'&&<div className="settings-grid"><div className="admin-panel asset-card"><div><span className="admin-mark">PROFILE PHOTO</span><h2>Profile image</h2><p>Update the live portfolio profile image.</p></div><img className="asset-preview profile-preview" src={profileUrl} alt="Current profile"/><label className="upload-btn big">Change profile photo<input type="file" accept="image/*" onChange={e=>uploadSiteAsset('profile',e.target.files?.[0]||null)}/></label></div><div className="admin-panel asset-card"><div><span className="admin-mark">RESUME</span><h2>Resume PDF</h2><p>Replace the live portfolio resume.</p></div><a href={resumeUrl} target="_blank" className="asset-link">Open current resume ↗</a><label className="upload-btn big">Replace resume PDF<input type="file" accept="application/pdf" onChange={e=>uploadSiteAsset('resume',e.target.files?.[0]||null)}/></label></div></div>}
  </section></main>
}
function Metric({label,value}:{label:string,value:number}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function VisitorTable({events}:{events:Event[]}){return <div className="table-wrap"><table><thead><tr><th>Time</th><th>Visitor</th><th>Event</th><th>Page</th><th>Device / browser</th><th>Language</th></tr></thead><tbody>{events.length?events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString()}</td><td><code>{e.visitor_id.slice(0,14)}…</code></td><td>{e.event_type}</td><td>{e.page}</td><td>{parseUA(e.user_agent)}</td><td>{e.language||'—'}</td></tr>):<tr><td colSpan={6}>No events are readable yet.</td></tr>}</tbody></table></div>}
function parseUA(ua:string|null){if(!ua)return '—';const b=ua.includes('Edg')?'Edge':ua.includes('Chrome')?'Chrome':ua.includes('Safari')?'Safari':ua.includes('Firefox')?'Firefox':'Browser';return `${/Mobi|Android/i.test(ua)?'Mobile':'Desktop'} · ${b}`}
