'use client';

import { useEffect, useMemo, useState } from 'react';
import { supabase, isSupabaseConfigured } from '../../lib/supabase';
import './admin.css';

type Project={id?:string;name:string;category:string;summary:string;impact:string;role:string[];tech:string[];screenshots:string[];live_url:string;github_url:string;featured:boolean;visible:boolean;sort_order:number};
type Skill={id?:string;category:string;name:string;sort_order:number;visible:boolean};
type Event={id:string;visitor_id:string;event_type:string;page:string;referrer:string|null;user_agent:string|null;language:string|null;timezone:string|null;created_at:string};

const emptyProject:Project={name:'',category:'',summary:'',impact:'',role:[],tech:[],screenshots:[],live_url:'',github_url:'',featured:false,visible:true,sort_order:0};
const categories=['Frontend','Backend','Data','Automation','DevOps','Integrations','Other'];

export default function Admin(){
 const [session,setSession]=useState<any>(null); const [loading,setLoading]=useState(true); const [tab,setTab]=useState('dashboard');
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
 const [projects,setProjects]=useState<Project[]>([]); const [skills,setSkills]=useState<Skill[]>([]); const [events,setEvents]=useState<Event[]>([]); const [editing,setEditing]=useState<Project|null>(null); const [skillName,setSkillName]=useState(''); const [skillCategory,setSkillCategory]=useState(categories[0]); const [saving,setSaving]=useState(false);
 const configured=isSupabaseConfigured && !!supabase;

 useEffect(()=>{if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);}); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>data.subscription.unsubscribe();},[]);
 useEffect(()=>{if(session) loadAll();},[session]);
 const loadAll=async()=>{if(!supabase)return; const [p,s,e]=await Promise.all([supabase.from('projects').select('*').order('sort_order'),supabase.from('skills').select('*').order('category').order('sort_order'),supabase.from('visitor_events').select('*').order('created_at',{ascending:false}).limit(500)]); if(p.data)setProjects(p.data); if(s.data)setSkills(s.data); if(e.data)setEvents(e.data);};
 const login=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!supabase){setError('Supabase is not configured yet.');return;} const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);};
 const logout=()=>supabase?.auth.signOut();
 const saveProject=async()=>{if(!supabase||!editing)return;setSaving(true);setError('');const payload={...editing,updated_at:new Date().toISOString()};const {data,error}=editing.id?await supabase.from('projects').update(payload).eq('id',editing.id).select().single():await supabase.from('projects').insert(payload).select().single();if(error)setError(error.message);else{await loadAll();setEditing(null);}setSaving(false);};
 const deleteProject=async(id?:string)=>{if(!supabase||!id||!confirm('Delete this project?'))return;const {error}=await supabase.from('projects').delete().eq('id',id);if(error)setError(error.message);else loadAll();};
 const uploadImages=async(files:FileList|null)=>{if(!supabase||!editing||!files)return;const urls=[...files].slice(0,8);for(const file of urls){const safe=file.name.toLowerCase().replace(/[^a-z0-9.-]+/g,'-');const path=`projects/${crypto.randomUUID()}-${safe}`;const {error}=await supabase.storage.from('portfolio').upload(path,file,{upsert:false,contentType:file.type});if(error){setError(error.message);return;}const {data}=supabase.storage.from('portfolio').getPublicUrl(path);editing.screenshots=[...editing.screenshots,data.publicUrl];setEditing({...editing});}};
 const addSkill=async()=>{if(!supabase||!skillName.trim())return;const {error}=await supabase.from('skills').insert({name:skillName.trim(),category:skillCategory,sort_order:skills.filter(s=>s.category===skillCategory).length,visible:true});if(error)setError(error.message);else{setSkillName('');loadAll();}};
 const deleteSkill=async(id?:string)=>{if(!supabase||!id)return;await supabase.from('skills').delete().eq('id',id);loadAll();};
 const uniqueVisitors=useMemo(()=>new Set(events.map(e=>e.visitor_id)).size,[events]); const views=events.filter(e=>e.event_type==='page_view').length; const resumeClicks=events.filter(e=>e.event_type==='resume_download').length; const contactClicks=events.filter(e=>e.event_type==='contact_click').length;
 if(loading)return <div className="admin-loading">Loading admin…</div>;
 if(!configured)return <main className="admin-shell"><div className="setup-card"><span className="admin-mark">ADMIN SETUP</span><h1>Connect your portfolio CMS.</h1><p>Add <code>NEXT_PUBLIC_SUPABASE_URL</code> and <code>NEXT_PUBLIC_SUPABASE_ANON_KEY</code> as GitHub Actions secrets, then deploy again. The exact SQL setup is in <code>supabase/schema.sql</code>.</p><ol><li>Create a Supabase project.</li><li>Run <code>supabase/schema.sql</code> in SQL Editor.</li><li>Create your email/password user in Authentication → Users.</li><li>Insert that user UUID into <code>admin_users</code>.</li><li>Add the two public Supabase environment variables to your GitHub Pages build.</li></ol></div></main>;
 if(!session)return <main className="admin-shell"><form className="login-card" onSubmit={login}><span className="admin-mark">PRIVATE · SUPER ADMIN</span><h1>Welcome back.</h1><p>Sign in to manage your portfolio and view private analytics.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="current-password"/></label>{error&&<div className="error">{error}</div>}<button className="admin-btn primary-btn">Sign in ↗</button><a className="back" href="/portfolio/">← Back to portfolio</a></form></main>;
 return <main className="admin-app"><aside><a href="/portfolio/" className="admin-brand">KV<span>ADMIN</span></a><button onClick={()=>setTab('dashboard')} className={tab==='dashboard'?'active':''}>◈ Dashboard</button><button onClick={()=>setTab('projects')} className={tab==='projects'?'active':''}>▣ Projects</button><button onClick={()=>setTab('skills')} className={tab==='skills'?'active':''}>✦ Skills</button><button onClick={()=>setTab('analytics')} className={tab==='analytics'?'active':''}>⌁ Analytics</button><div className="side-bottom"><button onClick={logout}>↪ Sign out</button></div></aside><section className="admin-main"><header className="admin-top"><div><span className="admin-mark">PORTFOLIO CONTROL CENTER</span><h1>{tab==='dashboard'?'Dashboard':tab[0].toUpperCase()+tab.slice(1)}</h1></div><a href="/portfolio/" target="_blank">View live site ↗</a></header>
 {error&&<div className="error global-error">{error}</div>}
 {tab==='dashboard'&&<div className="dashboard"><div className="metric-grid"><Metric label="Unique visitors" value={uniqueVisitors}/><Metric label="Page views" value={views}/><Metric label="Resume clicks" value={resumeClicks}/><Metric label="Contact clicks" value={contactClicks}/></div><div className="admin-panel"><div className="panel-head"><div><h2>Recent visitors</h2><p>Privacy-conscious activity. No raw IP addresses are stored.</p></div><button onClick={()=>setTab('analytics')}>Full analytics →</button></div><VisitorTable events={events.slice(0,10)}/></div></div>}
 {tab==='projects'&&<div className="admin-panel"><div className="panel-head"><div><h2>Projects</h2><p>Add projects, screenshots, technologies and case-study details.</p></div><button className="primary-btn" onClick={()=>setEditing({...emptyProject})}>+ Add project</button></div><div className="admin-list">{projects.map(p=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><small>{p.category} · {p.screenshots.length} screenshots</small></div><span className={p.visible?'published':'hidden'}>{p.visible?'Published':'Hidden'}</span><button onClick={()=>setEditing({...p})}>Edit</button><button className="danger" onClick={()=>deleteProject(p.id)}>Delete</button></div>)}</div></div>}
 {tab==='skills'&&<div className="admin-panel"><div className="panel-head"><div><h2>Skills</h2><p>Keep your technical toolbox current without editing code.</p></div></div><div className="skill-add"><input placeholder="e.g. Playwright" value={skillName} onChange={e=>setSkillName(e.target.value)}/><select value={skillCategory} onChange={e=>setSkillCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><button className="primary-btn" onClick={addSkill}>Add skill</button></div><div className="skill-admin-grid">{categories.map(c=><div key={c}><h3>{c}</h3>{skills.filter(s=>s.category===c).map(s=><div className="skill-admin-row" key={s.id}><span>{s.name}</span><button onClick={()=>deleteSkill(s.id)}>×</button></div>)}</div>)}</div></div>}
 {tab==='analytics'&&<div className="admin-panel"><div className="panel-head"><div><h2>Visitor analytics</h2><p>Shows activity collected by the portfolio. Visitors are represented by an anonymous browser ID.</p></div></div><div className="metric-grid"><Metric label="Unique visitors" value={uniqueVisitors}/><Metric label="Page views" value={views}/><Metric label="Resume clicks" value={resumeClicks}/><Metric label="Contact clicks" value={contactClicks}/></div><VisitorTable events={events}/></div>}
 {editing&&<ProjectModal project={editing} setProject={setEditing} save={saveProject} upload={uploadImages} saving={saving}/>}</section></main>;
}
function Metric({label,value}:{label:string,value:number}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function VisitorTable({events}:{events:Event[]}){return <div className="table-wrap"><table><thead><tr><th>Time</th><th>Visitor</th><th>Event</th><th>Page</th><th>Device / browser</th><th>Language</th></tr></thead><tbody>{events.length?events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString()}</td><td><code>{e.visitor_id.slice(0,12)}…</code></td><td>{e.event_type}</td><td>{e.page}</td><td>{parseUA(e.user_agent)}</td><td>{e.language||'—'}</td></tr>):<tr><td colSpan={6}>No visitor activity yet.</td></tr>}</tbody></table></div>}
function parseUA(ua:string|null){if(!ua)return '—';const browser=ua.includes('Edg')?'Edge':ua.includes('Chrome')?'Chrome':ua.includes('Safari')?'Safari':ua.includes('Firefox')?'Firefox':'Browser';const device=/Mobi|Android/i.test(ua)?'Mobile':'Desktop';return `${device} · ${browser}`;}
function ProjectModal({project,setProject,save,upload,saving}:{project:Project;setProject:(p:Project|null)=>void;save:()=>void;upload:(f:FileList|null)=>void;saving:boolean}){const update=(key:keyof Project,value:any)=>setProject({...project,[key]:value});return <div className="modal-backdrop"><div className="project-modal"><div className="modal-head"><div><span className="admin-mark">PROJECT EDITOR</span><h2>{project.id?'Edit project':'New project'}</h2></div><button onClick={()=>setProject(null)}>×</button></div><div className="form-grid"><label>Project name<input value={project.name} onChange={e=>update('name',e.target.value)}/></label><label>Category<input value={project.category} onChange={e=>update('category',e.target.value)}/></label><label className="wide">Summary<textarea rows={3} value={project.summary} onChange={e=>update('summary',e.target.value)}/></label><label className="wide">My impact<textarea rows={2} value={project.impact} onChange={e=>update('impact',e.target.value)}/></label><label className="wide">My contribution <span className="hint">one item per line</span><textarea rows={7} value={project.role.join('\n')} onChange={e=>update('role',e.target.value.split('\n').filter(Boolean))}/></label><label className="wide">Technologies <span className="hint">comma separated</span><input value={project.tech.join(', ')} onChange={e=>update('tech',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label>Live URL<input value={project.live_url} onChange={e=>update('live_url',e.target.value)} placeholder="https://…"/></label><label>GitHub URL<input value={project.github_url} onChange={e=>update('github_url',e.target.value)} placeholder="https://github.com/…"/></label></div><div className="checks"><label><input type="checkbox" checked={project.featured} onChange={e=>update('featured',e.target.checked)}/> Featured</label><label><input type="checkbox" checked={project.visible} onChange={e=>update('visible',e.target.checked)}/> Show publicly</label></div><div className="screens"><div className="screens-head"><div><h3>Screenshots</h3><p>Upload up to 8 images.</p></div><label className="upload-btn">+ Upload screenshots<input type="file" accept="image/*" multiple onChange={e=>upload(e.target.files)}/></label></div><div className="thumbs">{project.screenshots.map((url,i)=><div key={url} className="thumb"><img src={url} alt="Project screenshot"/><button onClick={()=>setProject({...project,screenshots:project.screenshots.filter((_,x)=>x!==i)})}>×</button></div>)}</div></div><div className="modal-actions"><button className="ghost-btn" onClick={()=>setProject(null)}>Cancel</button><button className="primary-btn" onClick={save} disabled={saving}>{saving?'Saving…':'Save project'}</button></div></div></div>}
