'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase,isSupabaseConfigured} from '../../lib/supabase';
import TeamPanel from './TeamPanel';
import './admin.css';
import './team/team.css';

type Project={id?:string;name:string;category:string;summary:string;impact:string;role:string[];tech:string[];screenshots:string[];live_url:string;github_url:string;featured:boolean;visible:boolean;sort_order:number};
type Skill={id?:string;category:string;name:string;sort_order:number;visible:boolean};
type Event={id:string;visitor_id:string;event_type:string;page:string;referrer:string|null;user_agent:string|null;language:string|null;timezone:string|null;created_at:string};
const BASE='/portfolio';
const emptyProject:Project={name:'',category:'',summary:'',impact:'',role:[],tech:[],screenshots:[],live_url:'',github_url:'',featured:false,visible:true,sort_order:0};
const categories=['Frontend','Backend','Data','Automation','DevOps','Integrations','Other'];

export default function Admin(){
  const[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState('dashboard'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[projects,setProjects]=useState<Project[]>([]),[skills,setSkills]=useState<Skill[]>([]),[events,setEvents]=useState<Event[]>([]),[editing,setEditing]=useState<Project|null>(null),[skillName,setSkillName]=useState(''),[skillCategory,setSkillCategory]=useState(categories[0]),[saving,setSaving]=useState(false),[profileUrl,setProfileUrl]=useState(`${BASE}/profile-320.jpg`),[resumeUrl,setResumeUrl]=useState(`${BASE}/resume.pdf`),[health,setHealth]=useState<Record<string,string>>({});
  const configured=isSupabaseConfigured&&!!supabase;
  useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[]);
  useEffect(()=>{if(session)loadAll()},[session]);

  const loadAll=async()=>{if(!supabase)return;setError('');const[p,s,e,a]=await Promise.all([supabase.from('projects').select('*').order('sort_order'),supabase.from('skills').select('*').order('category').order('sort_order'),supabase.from('visitor_events').select('*').order('created_at',{ascending:false}).limit(500),supabase.storage.from('portfolio').list('site')]);const h:Record<string,string>={};if(p.error)h.projects=p.error.message;else{setProjects(p.data||[]);h.projects=`Connected · ${p.data?.length||0} records`}if(s.error)h.skills=s.error.message;else{setSkills(s.data||[]);h.skills=`Connected · ${s.data?.length||0} records`}if(e.error)h.analytics=e.error.message;else{setEvents(e.data||[]);h.analytics=`Connected · ${e.data?.length||0} events`}if(a.error)h.storage=a.error.message;else{h.storage='Connected';const names=new Set((a.data||[]).map(x=>x.name));if(names.has('profile.jpg'))setProfileUrl(supabase.storage.from('portfolio').getPublicUrl('site/profile.jpg').data.publicUrl);if(names.has('resume.pdf'))setResumeUrl(supabase.storage.from('portfolio').getPublicUrl('site/resume.pdf').data.publicUrl)}setHealth(h)};
  const login=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!supabase){setError('Supabase is not configured yet.');return}const{error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message)};
  const logout=()=>supabase?.auth.signOut();
  const saveProject=async()=>{if(!supabase||!editing)return;setSaving(true);const payload={...editing,updated_at:new Date().toISOString()};delete (payload as any).id;const{error}=editing.id?await supabase.from('projects').update(payload).eq('id',editing.id):await supabase.from('projects').insert(payload);if(error)setError(error.message);else{await loadAll();setEditing(null);setNotice('Project saved.')}setSaving(false)};
  const deleteProject=async(id?:string)=>{if(!supabase||!id||!confirm('Delete this project?'))return;const{error}=await supabase.from('projects').delete().eq('id',id);if(error)setError(error.message);else loadAll()};
  const addSkill=async()=>{if(!supabase||!skillName.trim())return;const{error}=await supabase.from('skills').insert({name:skillName.trim(),category:skillCategory,sort_order:skills.filter(s=>s.category===skillCategory).length,visible:true});if(error)setError(error.message);else{setSkillName('');loadAll()}};
  const deleteSkill=async(id?:string)=>{if(!supabase||!id)return;const{error}=await supabase.from('skills').delete().eq('id',id);if(error)setError(error.message);else loadAll()};
  const uploadSiteAsset=async(kind:'profile'|'resume',file:File|null)=>{if(!supabase||!file)return;if(kind==='profile'&&!file.type.startsWith('image/'))return setError('Profile photo must be an image.');if(kind==='resume'&&file.type!=='application/pdf')return setError('Resume must be a PDF.');const path=kind==='profile'?'site/profile.jpg':'site/resume.pdf';const{error}=await supabase.storage.from('portfolio').upload(path,file,{contentType:file.type,upsert:true,cacheControl:'60'});if(error)return setError(error.message);const url=supabase.storage.from('portfolio').getPublicUrl(path).data.publicUrl;if(kind==='profile')setProfileUrl(`${url}?v=${Date.now()}`);else setResumeUrl(`${url}?v=${Date.now()}`);setNotice(`${kind==='profile'?'Profile photo':'Resume'} updated.`);await loadAll()};
  const testAnalytics=async()=>{if(!supabase)return;const{error}=await supabase.from('visitor_events').insert({visitor_id:`admin-test-${Date.now()}`,event_type:'admin_test',page:'/admin',referrer:null,user_agent:navigator.userAgent,language:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone});if(error)setError(error.message);else{setNotice('Analytics test succeeded.');loadAll()}};
  const uniqueVisitors=useMemo(()=>new Set(events.map(e=>e.visitor_id)).size,[events]),views=events.filter(e=>e.event_type==='page_view').length,resumeClicks=events.filter(e=>e.event_type==='resume_download').length,contactClicks=events.filter(e=>e.event_type==='contact_click').length;

  if(loading)return <div className="admin-loading">Loading admin…</div>;
  if(!configured)return <main className="admin-shell"><div className="setup-card"><span className="admin-mark">ADMIN SETUP</span><h1>Connect your portfolio CMS.</h1><p>Add your Supabase URL and anon key to GitHub Actions secrets, deploy again, then run the latest <code>supabase/schema.sql</code>.</p></div></main>;
  if(!session)return <main className="admin-shell"><form className="login-card" onSubmit={login}><span className="admin-mark">PRIVATE · PORTFOLIO ADMIN</span><h1>Welcome back.</h1><p>Manage projects, skills, analytics, team access and portfolio assets.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button className="admin-btn primary-btn">Sign in ↗</button></form></main>;

  const menu=[['dashboard','◈ Dashboard'],['projects','▣ Projects'],['skills','✦ Skills'],['analytics','⌁ Analytics'],['team','♟ Team & Access'],['settings','⚙ Settings']];
  return <main className="admin-app"><aside><a href={`${BASE}/`} className="admin-brand">VIBHU<span>ADMIN</span></a>{menu.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={tab===k?'active':''}>{l}</button>)}<div className="side-bottom"><button onClick={logout}>↪ Sign out</button></div></aside><section className="admin-main"><header className="admin-top"><div><span className="admin-mark">PORTFOLIO CONTROL CENTER</span><h1>{tab==='team'?'Team & Access':tab[0].toUpperCase()+tab.slice(1)}</h1></div><div className="admin-actions"><button onClick={loadAll}>Refresh</button><a href={`${BASE}/`} target="_blank">View live site ↗</a></div></header>{error&&<div className="error global-error">{error}</div>}{notice&&<div className="notice global-error">{notice}</div>}
  {tab==='dashboard'&&<><div className="metric-grid"><Metric label="Unique visitors" value={uniqueVisitors}/><Metric label="Page views" value={views}/><Metric label="Resume clicks" value={resumeClicks}/><Metric label="Contact clicks" value={contactClicks}/></div><div className="dashboard-grid"><div className="admin-panel"><div className="panel-head"><div><h2>Recent visitors</h2><p>Anonymous browser IDs only; no raw IP is stored.</p></div></div><VisitorTable events={events.slice(0,10)}/></div><div className="admin-panel health-panel"><div className="panel-head"><div><h2>Supabase health</h2><p>Live status of CMS, analytics and storage.</p></div></div>{Object.entries(health).map(([k,v])=><div className={'health-row '+(v.startsWith('Connected')?'ok':'bad')} key={k}><b>{k}</b><span>{v}</span></div>)}<button className="secondary-btn" onClick={testAnalytics}>Run analytics write test</button></div></div></>}
  {tab==='projects'&&<div className="admin-panel"><div className="panel-head"><div><h2>Projects</h2><p>Manage portfolio projects and visibility.</p></div><button className="primary-btn" onClick={()=>setEditing({...emptyProject,sort_order:projects.length})}>+ Add project</button></div><div className="admin-list">{projects.map(p=><div className="list-row" key={p.id}><div><strong>{p.name}</strong><small>{p.category}</small></div><span className={p.visible?'published':'hidden'}>{p.visible?'Published':'Hidden'}</span><button onClick={()=>setEditing({...p})}>Edit</button><button className="danger" onClick={()=>deleteProject(p.id)}>Delete</button></div>)}</div></div>}
  {tab==='skills'&&<div className="admin-panel"><div className="panel-head"><div><h2>Skills</h2><p>Manage technologies displayed on your portfolio.</p></div></div><div className="skill-add"><input placeholder="e.g. Playwright" value={skillName} onChange={e=>setSkillName(e.target.value)}/><select value={skillCategory} onChange={e=>setSkillCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><button className="primary-btn" onClick={addSkill}>Add skill</button></div><div className="skill-admin-grid">{categories.map(c=><div key={c}><h3>{c}</h3>{skills.filter(s=>s.category===c).map(s=><div className="skill-admin-row" key={s.id}><span>{s.name}</span><button onClick={()=>deleteSkill(s.id)}>×</button></div>)}</div>)}</div></div>}
  {tab==='analytics'&&<div className="admin-panel"><div className="panel-head"><div><h2>Visitor analytics</h2><p>Portfolio views and important actions.</p></div></div><div className="metric-grid"><Metric label="Unique visitors" value={uniqueVisitors}/><Metric label="Page views" value={views}/><Metric label="Resume clicks" value={resumeClicks}/><Metric label="Contact clicks" value={contactClicks}/></div><VisitorTable events={events}/></div>}
  {tab==='team'&&<TeamPanel session={session}/>} 
  {tab==='settings'&&<div className="settings-grid"><div className="admin-panel asset-card"><div><span className="admin-mark">PROFILE PHOTO</span><h2>Profile image</h2><p>Update the live portfolio profile image.</p></div><img className="asset-preview profile-preview" src={profileUrl} alt="Current profile"/><label className="upload-btn big">Change profile photo<input type="file" accept="image/*" onChange={e=>uploadSiteAsset('profile',e.target.files?.[0]||null)}/></label></div><div className="admin-panel asset-card"><div><span className="admin-mark">RESUME</span><h2>Resume PDF</h2><p>Replace the live portfolio resume.</p></div><a href={resumeUrl} target="_blank" className="asset-link">Open current resume ↗</a><label className="upload-btn big">Replace resume PDF<input type="file" accept="application/pdf" onChange={e=>uploadSiteAsset('resume',e.target.files?.[0]||null)}/></label></div></div>}
  {editing&&<ProjectModal project={editing} setProject={setEditing} save={saveProject} saving={saving}/>}</section></main>
}

function Metric({label,value}:{label:string,value:number}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
function VisitorTable({events}:{events:Event[]}){return <div className="table-wrap"><table><thead><tr><th>Time</th><th>Visitor</th><th>Event</th><th>Page</th><th>Device / browser</th><th>Language</th></tr></thead><tbody>{events.length?events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString()}</td><td><code>{e.visitor_id.slice(0,14)}…</code></td><td>{e.event_type}</td><td>{e.page}</td><td>{parseUA(e.user_agent)}</td><td>{e.language||'—'}</td></tr>):<tr><td colSpan={6}>No events are readable yet.</td></tr>}</tbody></table></div>}
function parseUA(ua:string|null){if(!ua)return '—';const b=ua.includes('Edg')?'Edge':ua.includes('Chrome')?'Chrome':ua.includes('Safari')?'Safari':ua.includes('Firefox')?'Firefox':'Browser';return `${/Mobi|Android/i.test(ua)?'Mobile':'Desktop'} · ${b}`}
function ProjectModal({project,setProject,save,saving}:{project:Project;setProject:(p:Project|null)=>void;save:()=>void;saving:boolean}){const u=(k:keyof Project,v:any)=>setProject({...project,[k]:v});return <div className="modal-backdrop"><div className="project-modal"><div className="modal-head"><div><span className="admin-mark">PROJECT EDITOR</span><h2>{project.id?'Edit project':'New project'}</h2></div><button onClick={()=>setProject(null)}>×</button></div><div className="form-grid"><label>Project name<input value={project.name} onChange={e=>u('name',e.target.value)}/></label><label>Category<input value={project.category} onChange={e=>u('category',e.target.value)}/></label><label className="wide">Summary<textarea rows={4} value={project.summary} onChange={e=>u('summary',e.target.value)}/></label><label className="wide">My impact<textarea rows={3} value={project.impact} onChange={e=>u('impact',e.target.value)}/></label><label className="wide">My contribution<textarea rows={8} value={project.role.join('\n')} onChange={e=>u('role',e.target.value.split('\n').filter(Boolean))}/></label><label className="wide">Technologies<input value={project.tech.join(', ')} onChange={e=>u('tech',e.target.value.split(',').map(x=>x.trim()).filter(Boolean))}/></label><label>Live URL<input value={project.live_url||''} onChange={e=>u('live_url',e.target.value)}/></label><label>GitHub URL<input value={project.github_url||''} onChange={e=>u('github_url',e.target.value)}/></label></div><div className="checks"><label><input type="checkbox" checked={project.featured} onChange={e=>u('featured',e.target.checked)}/> Featured</label><label><input type="checkbox" checked={project.visible} onChange={e=>u('visible',e.target.checked)}/> Show publicly</label></div><div className="modal-actions"><button className="ghost-btn" onClick={()=>setProject(null)}>Cancel</button><button className="primary-btn" onClick={save} disabled={saving}>{saving?'Saving…':'Save to Supabase'}</button></div></div></div>}
