'use client';

import {useEffect,useState} from 'react';
import {supabase} from '../../lib/supabase';

type Skill={id?:string;category:string;name:string;sort_order:number;visible:boolean};
const categories=['Frontend','Backend','Data','Automation','DevOps','Integrations','Other'];
const defaults=['HTML5','CSS3','JavaScript','TypeScript','React','Next.js','Node.js','Express.js','Python','FastAPI','MongoDB','PostgreSQL','Supabase','Docker','Playwright','n8n'];
const devicon:Record<string,string>={
'HTML5':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg','HTML':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg','CSS3':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg','CSS':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg','JavaScript':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg','TypeScript':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg','React':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg','React.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg','Next.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg','Node.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg','Express.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg','Express':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg','Python':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg','FastAPI':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fastapi/fastapi-original.svg','MongoDB':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg','PostgreSQL':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg','Supabase':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/supabase/supabase-original.svg','Docker':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg','Playwright':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/playwright/playwright-original.svg','n8n':'https://cdn.simpleicons.org/n8n/EA4B71'};

export default function SkillPanel({session}:{session:any}){
 const[items,setItems]=useState<Skill[]>([]),[name,setName]=useState(''),[category,setCategory]=useState('Frontend'),[err,setErr]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{bootstrap()},[]);
 const log=async(action:string,id:string,details:any)=>{if(!supabase)return;await supabase.from('activity_logs').insert({actor_user_id:session?.user?.id||null,action,entity_type:'skill',entity_id:id,details})};
 const load=async()=>{if(!supabase)return;const{data,error}=await supabase.from('skills').select('*').order('sort_order');if(error)setErr(error.message);else setItems(data||[])};
 const bootstrap=async()=>{if(!supabase)return;setBusy(true);const{data,error}=await supabase.from('skills').select('name');if(error){setErr(error.message);setBusy(false);return}const have=new Set((data||[]).map((x:any)=>x.name.toLowerCase()));const missing=defaults.filter(x=>!have.has(x.toLowerCase())).map((name,i)=>({name,category:'Frontend',sort_order:(data?.length||0)+i,visible:true}));if(missing.length)await supabase.from('skills').insert(missing);await load();setBusy(false)};
 const add=async()=>{if(!supabase||!name.trim())return;setBusy(true);setErr('');const payload={name:name.trim(),category,sort_order:items.length,visible:true};const{data,error}=await supabase.from('skills').insert(payload).select('id').single();if(error)setErr(error.message);else{await log('skill_added',data?.id||'',payload);setName('');setMsg('Skill added and published.');await load()}setBusy(false)};
 const toggle=async(x:Skill)=>{if(!supabase||!x.id)return;await supabase.from('skills').update({visible:!x.visible}).eq('id',x.id);await log('skill_visibility_changed',x.id,{name:x.name,visible:!x.visible});load()};
 const remove=async(x:Skill)=>{if(!supabase||!x.id||!confirm(`Remove ${x.name} from your portfolio?`))return;const{error}=await supabase.from('skills').delete().eq('id',x.id);if(error)setErr(error.message);else{await log('skill_deleted',x.id,{name:x.name});load()}};
 return <div className="cms-panel">{err&&<div className="error">{err}</div>}{msg&&<div className="notice">{msg}</div>}<div className="cms-head"><div><span className="admin-mark">SKILLS CMS</span><h2>Technologies & skills</h2><p>The same skills and icons shown on your public home page. Add, hide, publish or remove any skill.</p></div></div><div className="skill-builder"><input placeholder="Add a skill, e.g. AWS" value={name} onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()}/><select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select><button className="primary-btn" onClick={add} disabled={busy}>+ Add skill</button></div><div className="skill-card-grid">{items.map(x=><article className={'skill-cms-card '+(!x.visible?'is-hidden':'')} key={x.id}><div className="skill-icon-wrap">{devicon[x.name]?<img src={devicon[x.name]} alt=""/>:<b>{x.name.slice(0,2).toUpperCase()}</b>}</div><div className="skill-cms-main"><h3>{x.name}</h3><small>{x.category}</small></div><span className={x.visible?'published':'hidden'}>{x.visible?'LIVE':'HIDDEN'}</span><div className="skill-cms-actions"><button onClick={()=>toggle(x)}>{x.visible?'Hide':'Publish'}</button><button className="danger" onClick={()=>remove(x)}>Remove</button></div></article>)}</div></div>
}
