'use client';

import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../../lib/supabase';

const BASE='/portfolio';
const roles=['owner','admin','manager','developer','content_manager','viewer'];
const permissionKeys=[['view_dashboard','View dashboard'],['view_analytics','View analytics'],['manage_projects','Manage projects'],['add_projects','Add projects'],['edit_projects','Edit projects'],['delete_projects','Delete projects'],['manage_skills','Manage skills'],['upload_resume','Upload resume'],['manage_settings','Change portfolio settings'],['view_visitors','View visitors'],['manage_users','Manage users'],['approve_users','Approve users'],['assign_roles','Assign roles'],['upload_files','Upload images/files'],['publish_content','Publish/unpublish content']];
const presets:Record<string,string[]>={owner:permissionKeys.map(x=>x[0]),admin:permissionKeys.map(x=>x[0]),manager:['view_dashboard','view_analytics','manage_projects','add_projects','edit_projects','manage_skills','view_visitors','upload_files','publish_content'],developer:['view_dashboard','manage_projects','add_projects','edit_projects','manage_skills','upload_files'],content_manager:['view_dashboard','manage_projects','add_projects','edit_projects','manage_skills','upload_files','publish_content'],viewer:['view_dashboard','view_analytics','view_visitors']};

type Req={id:string;user_id:string|null;full_name:string;email:string;phone:string|null;job_title:string|null;experience:string|null;skills:string[];bio:string|null;linkedin_url:string|null;github_url:string|null;portfolio_url:string|null;avatar_url:string|null;reason:string|null;status:string;created_at:string};
type Profile={user_id:string;full_name:string;email:string;avatar_url:string|null;job_title:string|null;role:string;status:string;permissions:Record<string,boolean>;created_at:string;last_login_at:string|null};
type Activity={id:string;actor_user_id:string|null;action:string;entity_type:string|null;entity_id:string|null;details:any;created_at:string};

export default function TeamPanel({session}:{session:any}){
  const[requests,setRequests]=useState<Req[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[activity,setActivity]=useState<Activity[]>([]),[selected,setSelected]=useState<Req|null>(null),[editingMember,setEditingMember]=useState<Profile|null>(null),[role,setRole]=useState('developer'),[permissions,setPermissions]=useState<Record<string,boolean>>({}),[message,setMessage]=useState(''),[error,setError]=useState(''),[activityUser,setActivityUser]=useState('all'),[activityType,setActivityType]=useState('all');
  useEffect(()=>{if(session)load()},[session]);
  const load=async()=>{if(!supabase)return;setError('');const[r,p,a]=await Promise.all([supabase.from('access_requests').select('*').order('created_at',{ascending:false}),supabase.from('profiles').select('*').order('created_at',{ascending:false}),supabase.from('activity_logs').select('*').order('created_at',{ascending:false}).limit(200)]);if(r.error)setError(r.error.message);else setRequests(r.data||[]);if(p.error)setError(p.error.message);else setProfiles(p.data||[]);if(a.error)setError(a.error.message);else setActivity(a.data||[])};
  const rolePermissions=(r:string)=>Object.fromEntries(permissionKeys.map(([k])=>[k,(presets[r]||[]).includes(k)]));
  const choose=(r:Req)=>{setSelected(r);setRole('developer');setPermissions(rolePermissions('developer'));setMessage('')};
  const editMember=(p:Profile)=>{setEditingMember(p);setRole(p.role);setPermissions({...p.permissions});setMessage('')};
  const changeRole=(r:string)=>{setRole(r);setPermissions(rolePermissions(r))};
  const log=async(action:string,entityType:string,entityId:string,details:any={})=>{if(!supabase||!session)return;await supabase.from('activity_logs').insert({actor_user_id:session.user.id,action,entity_type:entityType,entity_id:entityId,details})};
  const approve=async()=>{if(!supabase||!selected)return;if(!selected.user_id){setError('This request has no Supabase Auth user ID. Ask the person to submit the request again.');return}const payload={user_id:selected.user_id,full_name:selected.full_name,email:selected.email,avatar_url:selected.avatar_url,job_title:selected.job_title,role,status:'active',permissions,updated_at:new Date().toISOString()};const{error:e1}=await supabase.from('profiles').upsert(payload,{onConflict:'user_id'});if(e1)return setError(e1.message);const{error:e2}=await supabase.from('access_requests').update({status:'approved',reviewed_at:new Date().toISOString(),reviewed_by:session.user.id}).eq('id',selected.id);if(e2)return setError(e2.message);await log('approved_user','profile',selected.user_id,{role,permissions,email:selected.email});setMessage(`${selected.full_name} approved as ${role.replace('_',' ')}.`);setSelected(null);await load()};
  const reject=async(r:Req)=>{if(!supabase||!confirm(`Reject ${r.full_name}?`))return;const{error}=await supabase.from('access_requests').update({status:'rejected',reviewed_at:new Date().toISOString(),reviewed_by:session.user.id}).eq('id',r.id);if(error)setError(error.message);else{await log('rejected_user','access_request',r.id,{email:r.email});load()}};
  const saveMember=async()=>{if(!supabase||!editingMember)return;const changes={role,permissions,updated_at:new Date().toISOString()};const{error}=await supabase.from('profiles').update(changes).eq('user_id',editingMember.user_id);if(error)return setError(error.message);await log('permissions_updated','profile',editingMember.user_id,{role,permissions,email:editingMember.email});setMessage(`Access updated for ${editingMember.full_name||editingMember.email}.`);setEditingMember(null);await load()};
  const toggleStatus=async(p:Profile)=>{if(!supabase)return;const status=p.status==='active'?'suspended':'active';if(status==='suspended'&&!confirm(`Suspend ${p.full_name||p.email}?`))return;const{error}=await supabase.from('profiles').update({status,updated_at:new Date().toISOString()}).eq('user_id',p.user_id);if(error)return setError(error.message);await log(status==='suspended'?'suspended_user':'reactivated_user','profile',p.user_id,{email:p.email});await load()};
  const counts=useMemo(()=>({pending:requests.filter(x=>x.status==='pending').length,active:profiles.filter(x=>x.status==='active').length,suspended:profiles.filter(x=>x.status==='suspended').length,managers:profiles.filter(x=>x.role==='manager'&&x.status==='active').length}),[requests,profiles]);
  const filteredActivity=useMemo(()=>activity.filter(a=>(activityUser==='all'||a.actor_user_id===activityUser||a.entity_id===activityUser)&&(activityType==='all'||a.action===activityType)),[activity,activityUser,activityType]);
  const nameFor=(id:string|null)=>profiles.find(p=>p.user_id===id)?.full_name||profiles.find(p=>p.user_id===id)?.email||'System';
  const actionTypes=Array.from(new Set(activity.map(a=>a.action)));
  return <div className="team-embedded">{error&&<div className="alert error">{error}</div>}{message&&<div className="alert ok">{message}</div>}
    <div className="embedded-team-head"><div><span className="mark">ACCESS COMMAND CENTER</span><h2>People, roles & permissions</h2><p>Approve users, reassign authority, suspend access and audit what your team is doing.</p></div><div className="top-actions"><a href={`${BASE}/access-request/`} target="_blank">Open request form ↗</a><button onClick={load}>Refresh</button></div></div>
    <section className="stats modern-stats"><Stat label="Pending" value={counts.pending} sub="Awaiting review"/><Stat label="Active" value={counts.active} sub="Can sign in"/><Stat label="Managers" value={counts.managers} sub="Elevated access"/><Stat label="Suspended" value={counts.suspended} sub="Access blocked"/></section>
    <section className="team-grid modern-team-grid"><div className="team-card"><div className="card-head"><div><h2>Access requests</h2><p>Nothing becomes active until you approve it.</p></div><span className="count-pill">{counts.pending}</span></div><div className="rows">{requests.filter(r=>r.status==='pending').length?requests.filter(r=>r.status==='pending').map(r=><div className="person-row request-row" key={r.id}><Avatar src={r.avatar_url} name={r.full_name}/><div className="person-main"><strong>{r.full_name}</strong><span>{r.email}</span><small>{r.job_title||'No title'} · {r.skills?.slice(0,3).join(', ')||'No skills listed'}</small></div><button onClick={()=>choose(r)}>Review</button><button className="danger" onClick={()=>reject(r)}>Reject</button></div>):<div className="empty">No pending requests.</div>}</div></div>
      <div className="team-card"><div className="card-head"><div><h2>Team members</h2><p>Full control over role, permissions and status.</p></div><span className="count-pill">{profiles.length}</span></div><div className="rows">{profiles.length?profiles.map(p=><div className="member-control" key={p.user_id}><div className="member-line"><Avatar src={p.avatar_url} name={p.full_name||p.email}/><div className="person-main"><strong>{p.full_name||p.email}</strong><span>{p.email}</span><small>{p.job_title||'Team member'}</small></div><span className={`role-badge role-${p.role}`}>{p.role.replace('_',' ')}</span><span className={`status-dot ${p.status}`}>{p.status}</span></div><div className="member-actions"><button onClick={()=>editMember(p)}>⚙ Edit access</button><button onClick={()=>setActivityUser(p.user_id)}>↗ View activity</button><button className={p.status==='active'?'warn':'success'} onClick={()=>toggleStatus(p)}>{p.status==='active'?'Suspend':'Reactivate'}</button></div></div>):<div className="empty">No approved team members yet.</div>}</div></div></section>
    <section className="team-card activity modern-activity"><div className="card-head activity-head"><div><span className="mark">AUDIT TRAIL</span><h2>Team activity</h2><p>See logins, approvals, role changes, project changes, uploads and other recorded actions.</p></div><div className="activity-filters"><select value={activityUser} onChange={e=>setActivityUser(e.target.value)}><option value="all">All people</option>{profiles.map(p=><option key={p.user_id} value={p.user_id}>{p.full_name||p.email}</option>)}</select><select value={activityType} onChange={e=>setActivityType(e.target.value)}><option value="all">All actions</option>{actionTypes.map(a=><option key={a} value={a}>{a.replaceAll('_',' ')}</option>)}</select></div></div><div className="activity-table"><div className="activity-header"><span>Person</span><span>Action</span><span>Target</span><span>Time</span></div>{filteredActivity.length?filteredActivity.slice(0,100).map(a=><div className="activity-row" key={a.id}><strong>{nameFor(a.actor_user_id)}</strong><span className="activity-action">{a.action.replaceAll('_',' ')}</span><span>{a.details?.name||a.details?.email||a.entity_type||'—'}</span><time>{new Date(a.created_at).toLocaleString()}</time></div>):<div className="empty">No activity matches these filters.</div>}</div></section>
    {selected&&<AccessModal title="Approve access" name={selected.full_name} email={selected.email} avatar={selected.avatar_url} role={role} permissions={permissions} onRole={changeRole} onPermissions={setPermissions} onClose={()=>setSelected(null)} onSave={approve} saveLabel="Approve & assign access" extra={<><div className="detail-grid"><Info label="Job title" value={selected.job_title}/><Info label="Experience" value={selected.experience}/><Info label="Phone" value={selected.phone}/><Info label="Skills" value={selected.skills?.join(', ')}/></div>{selected.reason&&<div className="detail-block"><b>Reason for access</b><p>{selected.reason}</p></div>}</>}/>} 
    {editingMember&&<AccessModal title="Edit team access" name={editingMember.full_name||editingMember.email} email={editingMember.email} avatar={editingMember.avatar_url} role={role} permissions={permissions} onRole={changeRole} onPermissions={setPermissions} onClose={()=>setEditingMember(null)} onSave={saveMember} saveLabel="Save permissions" extra={<div className="control-note"><strong>Current status: {editingMember.status}</strong><span>Role presets are a starting point. You can override every permission individually.</span></div>}/>} 
  </div>
}
function AccessModal({title,name,email,avatar,role,permissions,onRole,onPermissions,onClose,onSave,saveLabel,extra}:{title:string;name:string;email:string;avatar:string|null;role:string;permissions:Record<string,boolean>;onRole:(r:string)=>void;onPermissions:(p:Record<string,boolean>)=>void;onClose:()=>void;onSave:()=>void;saveLabel:string;extra:any}){return <div className="modal-back"><div className="review-modal access-editor"><button className="close" onClick={onClose}>×</button><div className="review-title"><Avatar src={avatar} name={name}/><div><span className="mark">{title.toUpperCase()}</span><h2>{name}</h2><p>{email}</p></div></div>{extra}<label className="role-field">Role<select value={role} onChange={e=>onRole(e.target.value)}>{roles.map(r=><option key={r} value={r}>{r.replace('_',' ')}</option>)}</select></label><div className="permissions"><div className="permission-title"><div><h3>Permissions</h3><p>Grant only what this person needs.</p></div><button onClick={()=>onPermissions(rolePermissionsLocal(role))}>Reset to {role.replace('_',' ')} preset</button></div><div className="permission-grid">{permissionKeys.map(([k,label])=><label className={permissions[k]?'enabled':''} key={k}><input type="checkbox" checked={!!permissions[k]} onChange={e=>onPermissions({...permissions,[k]:e.target.checked})}/><span>{label}</span></label>)}</div></div><div className="modal-actions"><button onClick={onClose}>Cancel</button><button className="approve" onClick={onSave}>{saveLabel} →</button></div></div></div>}
function rolePermissionsLocal(r:string){return Object.fromEntries(permissionKeys.map(([k])=>[k,(presets[r]||[]).includes(k)]))}
function Avatar({src,name}:{src:string|null;name:string}){return src?<img className="avatar" src={src} alt=""/>:<div className="avatar fallback">{name.slice(0,1).toUpperCase()}</div>}
function Stat({label,value,sub}:{label:string;value:number;sub:string}){return <div className="stat"><span>{label}</span><strong>{value}</strong><small>{sub}</small></div>}
function Info({label,value}:{label:string;value:string|null|undefined}){return <div><small>{label}</small><strong>{value||'—'}</strong></div>}
