'use client';

import {useEffect,useState} from 'react';
import {supabase,ensureFreshSession} from '../../lib/supabase';
import {defaultTheme,loadThemeConfig,ThemeConfig,ThemePalette} from '../ThemeRuntime';

const fields:[keyof ThemePalette,string][]=[['background','Background'],['panel','Cards / Panels'],['accent','Primary Accent'],['accent2','Secondary Accent'],['text','Main Text'],['muted','Muted Text'],['line','Borders']];

function applyAdmin(p:ThemePalette){const r=document.documentElement;r.style.setProperty('--adm-bg',p.background);r.style.setProperty('--adm-panel',p.panel);r.style.setProperty('--adm-accent',p.accent);r.style.setProperty('--adm-accent2',p.accent2);r.style.setProperty('--adm-text',p.text);r.style.setProperty('--adm-muted',p.muted);r.style.setProperty('--adm-line',p.line)}

export default function ThemeSettingsInline(){
 const[tab,setTab]=useState<'portfolio'|'admin'>('portfolio'),[theme,setTheme]=useState<ThemeConfig>(defaultTheme),[status,setStatus]=useState(''),[saving,setSaving]=useState(false);
 useEffect(()=>{(async()=>{const loaded=await loadThemeConfig();setTheme(loaded);applyAdmin(loaded.admin)})()},[]);
 const palette=theme[tab];
 const change=(key:keyof ThemePalette,value:string)=>{const next={...theme,[tab]:{...palette,[key]:value}};setTheme(next);if(tab==='admin')applyAdmin(next.admin)};
 const reset=()=>{const next={...theme,[tab]:{...defaultTheme[tab]}};setTheme(next);if(tab==='admin')applyAdmin(next.admin)};
 const save=async()=>{if(!supabase)return;setSaving(true);setStatus('');const session=await ensureFreshSession();if(!session){setStatus('Session expired. Please sign in again.');setSaving(false);return}const body=JSON.stringify(theme,null,2);const blob=new Blob([body],{type:'application/json'});const{error}=await supabase.storage.from('portfolio').upload('site/theme.json',blob,{upsert:true,contentType:'application/json',cacheControl:'60'});if(error)setStatus(error.message);else{localStorage.setItem('portfolio-theme-cache',body);setStatus('Theme saved successfully.')}setSaving(false)};
 return <section className='admin-panel theme-inline'><div className='panel-head'><div><span className='admin-mark'>APPEARANCE</span><h2>Theme Settings</h2><p>Manage your public portfolio and Admin appearance from one place.</p></div></div><div className='theme-inline-tabs'><button className={tab==='portfolio'?'active':''} onClick={()=>setTab('portfolio')}>Portfolio Theme</button><button className={tab==='admin'?'active':''} onClick={()=>setTab('admin')}>Admin Theme</button></div><div className='theme-inline-preview' style={{background:palette.background,borderColor:palette.line,color:palette.text}}><div style={{background:palette.panel,borderColor:palette.line}}><span><i style={{background:palette.accent}}/><i style={{background:palette.accent2}}/></span><strong>{tab==='portfolio'?'Public Portfolio':'Admin Control Center'}</strong><small style={{color:palette.muted}}>Live palette preview</small><button style={{background:`linear-gradient(135deg,${palette.accent},${palette.accent2})`}}>Primary action</button></div></div><div className='theme-inline-fields'>{fields.map(([key,label])=><label key={key}><span>{label}<code>{palette[key]}</code></span><div><input type='color' value={palette[key]} onChange={e=>change(key,e.target.value)}/><input value={palette[key]} onChange={e=>change(key,e.target.value)} maxLength={7}/></div></label>)}</div><div className='theme-inline-actions'><button className='secondary-btn' onClick={reset}>Reset {tab}</button><button className='primary-btn' onClick={save} disabled={saving}>{saving?'Saving…':'Save Theme'}</button>{status&&<small>{status}</small>}</div><style>{`
.theme-inline{grid-column:1/-1}.theme-inline-tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:18px 0}.theme-inline-tabs button{border:1px solid var(--adm-line,#263141);background:var(--adm-panel,#101622);color:var(--adm-muted,#8e9aa8);padding:12px;border-radius:10px;font-weight:800;cursor:pointer}.theme-inline-tabs button.active{background:linear-gradient(135deg,var(--adm-accent,#7c5cff),var(--adm-accent2,#3fd4ff));color:#fff;border-color:transparent}.theme-inline-preview{border:1px solid;border-radius:16px;padding:14px;margin-bottom:18px}.theme-inline-preview>div{border:1px solid;border-radius:13px;padding:18px;display:grid;gap:7px}.theme-inline-preview span{display:flex;gap:6px}.theme-inline-preview i{width:12px;height:12px;border-radius:50%}.theme-inline-preview strong{font-size:20px}.theme-inline-preview button{margin-top:7px;width:max-content;border:0;color:#fff;padding:9px 13px;border-radius:8px}.theme-inline-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.theme-inline-fields label{border:1px solid var(--adm-line,#263141);background:var(--adm-panel,#101622);border-radius:12px;padding:12px}.theme-inline-fields label>span{display:flex;justify-content:space-between;gap:8px;font-size:11px;font-weight:800}.theme-inline-fields code{font-size:9px;color:var(--adm-muted,#8e9aa8)}.theme-inline-fields label>div{display:grid;grid-template-columns:45px 1fr;gap:8px;margin-top:9px}.theme-inline-fields input[type=color]{width:45px;height:36px;border:0;padding:0;background:none}.theme-inline-fields input:not([type=color]){width:100%;background:var(--adm-bg,#080b12);color:var(--adm-text,#fff);border:1px solid var(--adm-line,#263141);border-radius:8px;padding:8px}.theme-inline-actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap;margin-top:16px}.theme-inline-actions small{color:var(--adm-muted,#8e9aa8)}@media(max-width:650px){.theme-inline-fields{grid-template-columns:1fr}.theme-inline-tabs{grid-template-columns:1fr}}
`}</style></section>
}
