'use client';

import {FormEvent,useState} from 'react';
import {supabase,isSupabaseConfigured} from '../../lib/supabase';
import './request.css';

const BASE='/portfolio';

type FormState={fullName:string;email:string;password:string;phone:string;jobTitle:string;experience:string;skills:string;bio:string;linkedin:string;github:string;portfolio:string;reason:string};
const initial:FormState={fullName:'',email:'',password:'',phone:'',jobTitle:'',experience:'',skills:'',bio:'',linkedin:'',github:'',portfolio:'',reason:''};

export default function AccessRequestPage(){
  const[form,setForm]=useState(initial);const[avatar,setAvatar]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[done,setDone]=useState(false);const[showPassword,setShowPassword]=useState(false);
  const set=(k:keyof FormState,v:string)=>setForm(p=>({...p,[k]:v}));
  const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(!supabase||!isSupabaseConfigured){setError('Access system is not configured yet.');return}if(form.password.length<8){setError('Password must be at least 8 characters.');return}setBusy(true);
    let avatarUrl='';
    if(avatar){const safe=avatar.name.toLowerCase().replace(/[^a-z0-9.-]+/g,'-');const path=`access/${crypto.randomUUID()}-${safe}`;const up=await supabase.storage.from('portfolio').upload(path,avatar,{contentType:avatar.type});if(up.error){setError(up.error.message);setBusy(false);return}avatarUrl=supabase.storage.from('portfolio').getPublicUrl(path).data.publicUrl}
    const sign=await supabase.auth.signUp({email:form.email.trim(),password:form.password,options:{data:{full_name:form.fullName.trim()}}});if(sign.error){setError(sign.error.message);setBusy(false);return}
    const{error:insertError}=await supabase.from('access_requests').insert({user_id:sign.data.user?.id||null,full_name:form.fullName.trim(),email:form.email.trim(),phone:form.phone.trim()||null,job_title:form.jobTitle.trim()||null,experience:form.experience.trim()||null,skills:form.skills.split(',').map(x=>x.trim()).filter(Boolean),bio:form.bio.trim()||null,linkedin_url:form.linkedin.trim()||null,github_url:form.github.trim()||null,portfolio_url:form.portfolio.trim()||null,avatar_url:avatarUrl||null,reason:form.reason.trim()||null,status:'pending'});
    if(insertError){setError(insertError.message);setBusy(false);return}setDone(true);setBusy(false)
  };
  if(done)return <main className="request-shell"><section className="request-card success-card"><span className="eyebrow">ACCESS REQUEST SENT</span><h1>Application received.</h1><p>Your account request has been sent to the portfolio owner for review. You will be able to use the admin area after approval.</p><a href={`${BASE}/admin/`}>Go to admin login →</a></section></main>;
  return <main className="request-shell"><section className="request-card"><div className="request-head"><div><span className="eyebrow">PORTFOLIO TEAM ACCESS</span><h1>Request an account.</h1><p>Create your login and share your professional details. Access stays pending until an administrator assigns your role and permissions.</p></div><a href={`${BASE}/`}>← Portfolio</a></div><form onSubmit={submit} className="request-form"><div className="grid two"><label>Full name<input value={form.fullName} onChange={e=>set('fullName',e.target.value)} required/></label><label>Email<input type="email" value={form.email} onChange={e=>set('email',e.target.value)} required/></label></div><div className="grid two"><label>Password<div className="password-field"><input type={showPassword?'text':'password'} value={form.password} onChange={e=>set('password',e.target.value)} minLength={8} required/><button type="button" className="eye-btn" onClick={()=>setShowPassword(v=>!v)} aria-label={showPassword?'Hide password':'Show password'}>{showPassword?'🙈':'👁'}</button></div><small>Minimum 8 characters. Password is stored securely by Supabase Auth.</small><a className="forgot-inline" href={`${BASE}/forgot-password/`}>Forgot your password?</a></label><label>Profile image<input type="file" accept="image/*" onChange={e=>setAvatar(e.target.files?.[0]||null)}/></label></div><div className="grid two"><label>Phone<input value={form.phone} onChange={e=>set('phone',e.target.value)}/></label><label>Current / requested job title<input value={form.jobTitle} onChange={e=>set('jobTitle',e.target.value)} placeholder="Developer, Manager, Designer..."/></label></div><div className="grid two"><label>Experience<input value={form.experience} onChange={e=>set('experience',e.target.value)} placeholder="e.g. 4 years"/></label><label>Skills<input value={form.skills} onChange={e=>set('skills',e.target.value)} placeholder="React, Node.js, Supabase"/><small>Separate skills with commas.</small></label></div><label>Short bio<textarea value={form.bio} onChange={e=>set('bio',e.target.value)} rows={4}/></label><div className="grid three"><label>LinkedIn<input value={form.linkedin} onChange={e=>set('linkedin',e.target.value)} placeholder="https://..."/></label><label>GitHub<input value={form.github} onChange={e=>set('github',e.target.value)} placeholder="https://..."/></label><label>Portfolio<input value={form.portfolio} onChange={e=>set('portfolio',e.target.value)} placeholder="https://..."/></label></div><label>Why do you need access?<textarea value={form.reason} onChange={e=>set('reason',e.target.value)} rows={3}/></label>{error&&<div className="form-error">{error}</div>}<button disabled={busy}>{busy?'Submitting…':'Submit access request →'}</button></form></section></main>
}
