'use client';

import {useParams} from 'next/navigation';
import {useEffect,useState} from 'react';
import {api,post} from '@/lib/api';

export default function JobDetail(){
 const{id}=useParams<{id:string}>();const[job,setJob]=useState<any>(null),[draft,setDraft]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=async()=>{try{setJob(await api(`/api/v1/jobs/${id}`))}catch(e:any){setError(e.message)}};useEffect(()=>{if(id)load()},[id]);
 const prepare=async()=>{setBusy(true);setError('');try{setDraft(await post('/api/v1/applications/prepare',{job_id:id,questions:[]}));await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 if(!job)return <div className='card'>{error||'Loading job…'}</div>;
 const match=job.job_matches?.[0],app=job.applications?.[0];
 return <div className='space-y-6'><header className='card'><div className='flex flex-col gap-5 md:flex-row md:items-start md:justify-between'><div><div className='flex flex-wrap gap-2'><span className='pill'>{job.source_key}</span><span className='pill'>{app?.status||'found'}</span>{job.remote&&<span className='pill'>Remote</span>}</div><h1 className='mt-4 text-4xl font-black'>{job.title}</h1><p className='mt-2 text-lg text-slate-300'>{job.company}{job.location?` · ${job.location}`:''}</p></div><div className='text-left md:text-right'><div className='text-5xl font-black text-cyan'>{Math.round(match?.score||0)}</div><div className='eyebrow mt-1'>MATCH</div></div></div><div className='mt-5 flex flex-wrap gap-2'><a href={job.url} target='_blank' rel='noreferrer' className='btn'>Open source ↗</a><button className='btn btn-primary' onClick={prepare} disabled={busy}>{busy?'Preparing…':'Prepare tailored application'}</button></div></header>
 {error&&<div className='rounded-xl border border-red-400/30 bg-red-500/10 p-3 text-sm text-red-200'>{error}</div>}
 <section className='grid gap-5 xl:grid-cols-[1.4fr_.8fr]'><article className='card'><span className='eyebrow'>FULL DESCRIPTION</span><div className='mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-300'>{job.description||'No description stored.'}</div></article><aside className='space-y-5'><article className='card'><span className='eyebrow'>WHY IT MATCHES</span><div className='mt-4 grid gap-3'>{(match?.reasons||[]).map((x:string)=><p key={x} className='text-sm text-slate-300'>• {x}</p>)}</div>{match?.missing_skills?.length?<div className='mt-5'><div className='text-xs font-bold text-amber-300'>Potential missing skills</div><div className='mt-2 flex flex-wrap gap-2'>{match.missing_skills.map((x:string)=><span className='pill' key={x}>{x}</span>)}</div></div>:null}</article><article className='card'><span className='eyebrow'>SCORE BREAKDOWN</span><div className='mt-4 space-y-2 text-sm'>{[['Skills',match?.skill_score],['Role',match?.role_score],['Experience',match?.experience_score],['Location',match?.location_score],['Freshness',match?.freshness_score],['Compensation',match?.compensation_score],['Quality',match?.quality_score]].map(([label,value])=><div className='flex justify-between border-b border-line py-2 last:border-0' key={String(label)}><span className='text-muted'>{label}</span><b>{Math.round(Number(value||0))}</b></div>)}</div></article></aside></section>
 {(draft||app?.cover_letter)&&<section className='card'><span className='eyebrow'>APPLICATION DRAFT · APPROVAL REQUIRED</span><h2 className='mt-2 text-2xl font-black'>Tailored application package</h2><p className='muted mt-2'>Preparing this does not submit anything. Review it in the approval center before any supported external action.</p><pre className='mt-4 overflow-auto whitespace-pre-wrap rounded-xl border border-line bg-ink p-4 text-xs leading-6 text-slate-300'>{JSON.stringify(draft?.draft||app,null,2)}</pre></section>}
 </div>
}
