'use client';

const points=[
 [15,46],[20,30],[26,18],[36,12],[49,10],[62,13],[74,20],[82,31],[86,43],[84,55],[77,66],[66,73],[52,76],[39,73],[27,66],[19,57],
 [30,35],[38,27],[48,23],[59,25],[69,33],[72,45],[68,56],[57,63],[45,62],[35,56],[30,46],[42,39],[53,35],[61,43],[55,51],[44,49],
 [26,44],[35,18],[69,18],[78,40],[74,59],[51,69],[31,61]
] as const;

function edges(){const out:[number,number][]=[];for(let i=0;i<points.length;i++){for(let j=i+1;j<points.length;j++){const dx=points[i][0]-points[j][0],dy=points[i][1]-points[j][1],d=Math.sqrt(dx*dx+dy*dy);if(d<23&&(i+j)%3!==0)out.push([i,j])}}return out.slice(0,92)}
const links=edges();

export default function NeuralJarvisSkin(){
 return <>
  <div className='neural-jarvis-visual' aria-hidden='true'>
   <svg viewBox='0 0 100 86' role='presentation'>
    <defs><filter id='nGlow'><feGaussianBlur stdDeviation='1.8' result='b'/><feMerge><feMergeNode in='b'/><feMergeNode in='SourceGraphic'/></feMerge></filter></defs>
    <g className='neural-lines'>{links.map(([a,b],i)=><line key={i} x1={points[a][0]} y1={points[a][1]} x2={points[b][0]} y2={points[b][1]} style={{animationDelay:`${(i%17)*.07}s`}}/>)}</g>
    <g className='neural-nodes'>{points.map(([x,y],i)=><circle key={i} cx={x} cy={y} r={i%7===0?2.15:i%4===0?1.65:1.25} style={{animationDelay:`${(i%13)*.11}s`}}/>)}</g>
   </svg>
  </div>
  <style>{`
.neural-jarvis-visual{position:fixed;right:16px;bottom:17px;width:126px;height:104px;z-index:101;pointer-events:none;filter:drop-shadow(0 0 15px color-mix(in srgb,var(--pf-accent2,#3fd4ff) 35%,transparent));transform-origin:center;animation:neuralFloat 5.2s ease-in-out infinite}.neural-jarvis-visual:before{content:'';position:absolute;inset:9% 11%;border-radius:48% 52% 45% 55%/55% 44% 56% 45%;background:radial-gradient(circle at 50% 50%,color-mix(in srgb,var(--pf-accent2,#3fd4ff) 9%,transparent),transparent 67%);filter:blur(8px);animation:neuralAura 3.4s ease-in-out infinite}.neural-jarvis-visual svg{width:100%;height:100%;overflow:visible;position:relative;z-index:1}.neural-lines line{stroke:color-mix(in srgb,var(--pf-accent2,#3fd4ff) 58%,#d7e8ff);stroke-width:.46;stroke-linecap:round;opacity:.32;stroke-dasharray:26;stroke-dashoffset:26;animation:neuralBuild 3.8s ease-in-out infinite}.neural-lines line:nth-child(3n){stroke:color-mix(in srgb,var(--pf-accent,#7c5cff) 62%,#e5ddff);opacity:.4}.neural-nodes circle{fill:color-mix(in srgb,var(--pf-accent2,#3fd4ff) 55%,#fff);stroke:#eefcff;stroke-width:.22;filter:url(#nGlow);opacity:.78;transform-box:fill-box;transform-origin:center;animation:nodePulse 2.7s ease-in-out infinite}.neural-nodes circle:nth-child(4n){fill:color-mix(in srgb,var(--pf-accent,#7c5cff) 55%,#fff)}
.jarvis-shell .jarvis-orb{width:126px!important;height:104px!important;border:0!important;background:transparent!important;box-shadow:none!important;border-radius:0!important;filter:none!important;animation:none!important}.jarvis-shell .jarvis-orb:before,.jarvis-shell .jarvis-orb:after,.jarvis-shell .jarvis-orb .hud,.jarvis-shell .jarvis-orb .energy-beam,.jarvis-shell .jarvis-orb .jarvis-core{display:none!important}.jarvis-shell .jarvis-label{right:118px!important;bottom:37px!important;color:var(--pf-muted,#9ca3b4)!important}.jarvis-shell .jarvis-label i{background:var(--pf-accent2,#3fd4ff)!important;box-shadow:0 0 12px var(--pf-accent2,#3fd4ff)!important}
.jarvis-shell .jarvis-panel{background:linear-gradient(180deg,color-mix(in srgb,var(--pf-panel,#111421) 96%,#000),color-mix(in srgb,var(--pf-bg,#090b12) 98%,#000))!important;border-color:var(--pf-line,#252a3b)!important;box-shadow:0 30px 100px rgba(0,0,0,.58),0 0 52px color-mix(in srgb,var(--pf-accent2,#3fd4ff) 12%,transparent)!important;color:var(--pf-text,#f7f8fb)!important}.jarvis-shell .jarvis-panel header{background:linear-gradient(90deg,color-mix(in srgb,var(--pf-panel,#111421) 96%,#000),color-mix(in srgb,var(--pf-accent,#7c5cff) 10%,var(--pf-panel,#111421)))!important;border-color:var(--pf-line,#252a3b)!important}.jarvis-shell .jarvis-panel header b,.jarvis-shell .jarvis-msg.user{color:var(--pf-text,#f7f8fb)!important}.jarvis-shell .jarvis-heading small,.jarvis-shell .jarvis-panel footer,.jarvis-shell .jarvis-msg.assistant{color:var(--pf-muted,#9ca3b4)!important}.jarvis-shell .jarvis-msg.assistant{background:color-mix(in srgb,var(--pf-panel,#111421) 88%,#000)!important;border-color:var(--pf-line,#252a3b)!important;box-shadow:inset 2px 0 0 color-mix(in srgb,var(--pf-accent2,#3fd4ff) 45%,transparent)!important}.jarvis-shell .jarvis-msg.user{background:color-mix(in srgb,var(--pf-accent,#7c5cff) 28%,var(--pf-panel,#111421))!important;border-color:color-mix(in srgb,var(--pf-accent,#7c5cff) 48%,var(--pf-line,#252a3b))!important}.jarvis-shell .jarvis-prompts button,.jarvis-shell .jarvis-panel input{background:color-mix(in srgb,var(--pf-panel,#111421) 92%,#000)!important;border-color:var(--pf-line,#252a3b)!important;color:var(--pf-text,#f7f8fb)!important}.jarvis-shell .jarvis-panel form button{background:linear-gradient(135deg,var(--pf-accent,#7c5cff),var(--pf-accent2,#3fd4ff))!important}.jarvis-shell .jarvis-welcome{background:linear-gradient(135deg,color-mix(in srgb,var(--pf-panel,#111421) 97%,#000),color-mix(in srgb,var(--pf-accent,#7c5cff) 14%,var(--pf-panel,#111421)))!important;border-color:var(--pf-line,#252a3b)!important;color:var(--pf-text,#f7f8fb)!important}.jarvis-shell .jw-orb{background:radial-gradient(circle,var(--pf-accent2,#3fd4ff),var(--pf-accent,#7c5cff) 55%,var(--pf-bg,#090b12) 80%)!important}.jarvis-shell .jw-copy small,.jarvis-shell .jarvis-panel footer span,.jarvis-shell .input-prompt{color:var(--pf-accent2,#3fd4ff)!important}
@keyframes neuralBuild{0%{stroke-dashoffset:26;opacity:.08}35%{stroke-dashoffset:0;opacity:.54}70%{stroke-dashoffset:0;opacity:.27}100%{stroke-dashoffset:-26;opacity:.08}}@keyframes nodePulse{0%,100%{opacity:.42;transform:scale(.72)}40%{opacity:1;transform:scale(1.2)}65%{opacity:.72;transform:scale(.92)}}@keyframes neuralFloat{0%,100%{transform:translateY(0) rotate(-1deg)}50%{transform:translateY(-5px) rotate(1.2deg)}}@keyframes neuralAura{0%,100%{opacity:.35;transform:scale(.9)}50%{opacity:.9;transform:scale(1.12)}}
@media(max-width:600px){.neural-jarvis-visual{right:2px;bottom:4px;width:108px;height:90px}.jarvis-shell .jarvis-orb{width:108px!important;height:90px!important}.jarvis-shell .jarvis-panel{bottom:88px!important}.jarvis-shell .jarvis-welcome{bottom:91px!important}}
`}</style>
 </>
}
