const skills={Frontend:['React.js','Next.js','React Native','TypeScript','JavaScript','Redux','Tailwind CSS','Chakra UI'],Backend:['Node.js','Express.js','Python','FastAPI','RESTful APIs'],Databases:['Supabase','MongoDB','MySQL','PostgreSQL'],Automation:['Playwright','Web Scraping','n8n'],DevOps:['Docker','Docker Compose','Nginx','DigitalOcean'],Other:['Git','GitHub','Web3 / Blockchain']};

const projects=[
{name:"Bird's Eye Markets",category:'Real Estate Intelligence SaaS',purpose:'A platform that combines property, ownership, valuation and demographic data into property reports and market-analysis dashboards.',role:['Built Next.js frontend and dashboards.','Designed Node.js/Express APIs and Python/FastAPI services.','Built Playwright automation and third-party data workflows.','Automated recurring workflows with n8n.','Containerized and supported deployment with Docker, Nginx and DigitalOcean.'],tech:['Next.js','React','TypeScript','Node.js','Express.js','Python','FastAPI','Supabase','Playwright','n8n','Docker','Nginx','DigitalOcean','Stripe']},
{name:'Queflic',category:'Social Media Mobile Application',purpose:'A social network with profiles, feeds, photo/video posts and live photo moments combining photos with short video clips.',role:['Designed REST APIs for feeds, posts and media uploads.','Designed MongoDB data models.','Built media handling workflows.','Contributed to React Native development.'],tech:['React Native','Node.js','Express.js','MongoDB','REST APIs']},
{name:'Paradise Rental',category:'Property Rental Marketplace',purpose:'A marketplace where users can browse property listings, view details and book stays.',role:['Led development from requirements to product.','Built React UI for listings and booking flows.','Built Node.js/Express APIs for listings, bookings and authentication.','Worked with MongoDB and MySQL.'],tech:['React.js','Node.js','Express.js','MongoDB','MySQL','JWT']},
{name:'QuickKart',category:'E-commerce Web Application',purpose:'An e-commerce application for product browsing, cart management, checkout and order history.',role:['Built the React storefront.','Built APIs for products, authentication and orders.','Modeled product, user and order data.','Implemented JWT authentication and checkout integration.'],tech:['React.js','Node.js','Express.js','MongoDB','JWT','REST APIs']},
{name:'Informed.pro',category:'Professional Network for Medical Professionals',purpose:'A professional network where medical professionals can create profiles, connect and access curated knowledge and opportunities.',role:['Built MERN features for profiles and dynamic feeds.','Optimized data-heavy pages with pagination and MongoDB indexing.','Implemented authentication and role-based access.','Built Redux-powered dashboards.'],tech:['React.js','Redux','Node.js','Express.js','MongoDB','REST APIs']},
{name:'Docintel',category:'AI-Powered Clinical Research Application',purpose:'An application that helps clinicians discover relevant research with AI-curated content, saved articles and CPD tracking.',role:['Built features for AI-curated article feeds.','Built saved-article and CPD-tracking features.','Built REST APIs and responsive UI components.'],tech:['React.js','Node.js','Express.js','MongoDB','REST APIs']}
];

export default function Home(){
 return <main>
  <nav><b>Kumar Vibhu</b><div><a href="#about">About</a><a href="#experience">Experience</a><a href="#projects">Projects</a><a href="#skills">Skills</a><a className="navcta" href="#contact">Contact</a></div></nav>
  <header className="hero" id="about">
   <div className="eyebrow">FULL-STACK DEVELOPER · 3.5+ YEARS EXPERIENCE</div>
   <h1>Building <em>production-ready</em> web and mobile applications.</h1>
   <p>Full-Stack Developer with experience across frontend, backend, databases, APIs, automation, web scraping and cloud deployment.</p>
   <p><a className="primary" href="#projects">Explore my projects →</a><a className="secondary" href="mailto:kumar.vibhu.id@gmail.com">Contact me</a></p>
  </header>
  <section id="experience"><label>PROFESSIONAL EXPERIENCE</label><h2>Where I have built products</h2><div className="timeline"><article><small>FEB 2024 — PRESENT</small><h3>Full-Stack Developer</h3><b>WebNext Technologies · Mohali</b><p>Working across production web applications, APIs, data workflows, automation and infrastructure.</p></article><article><small>DEC 2022 — JAN 2024</small><h3>MERN Stack Developer</h3><b>ShineDezign · Mohali</b><p>Built full-stack product features, APIs, authentication systems and dashboards.</p></article></div></section>
  <section id="projects"><label>PROJECT PORTFOLIO</label><h2>What I built, how it works & the technology behind it</h2><p className="muted">Each project explains the product, my contribution and the technologies used.</p><div className="grid">{projects.map(p=><article key={p.name}><code>{p.category}</code><h3>{p.name}</h3><h4>What is it?</h4><p>{p.purpose}</p><h4>What I worked on</h4><ul>{p.role.map(x=><li key={x}>{x}</li>)}</ul><h4>Technology used</h4><div className="tags">{p.tech.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></section>
  <section id="skills"><label>TECHNICAL SKILLS</label><h2>Technologies I work with</h2><div className="stack">{Object.entries(skills).map(([k,v])=><div key={k}><h3>{k}</h3>{v.map(i=><span key={i}>{i}</span>)}</div>)}</div></section>
  <section id="contact" className="contact"><label>OPEN TO OPPORTUNITIES</label><h2>Let's connect.</h2><p>I am using this portfolio to showcase my work and explore Full-Stack Developer opportunities.</p><a href="mailto:kumar.vibhu.id@gmail.com">kumar.vibhu.id@gmail.com</a><a href="tel:+919816399109">+91 98163 99109</a></section>
  <footer>© 2026 Kumar Vibhu <span>Full-Stack Developer</span></footer>
 </main>;
}
