'use client';
import {useEffect} from 'react';
import {supabase,isSupabaseConfigured} from '../lib/supabase';

const skills=[['HTML5','HTML'],['CSS3','CSS'],['JavaScript','JS'],['TypeScript','TS'],['React','⚛'],['Node.js','⬡'],['Express.js','ex'],['MongoDB','◉'],['Tailwind CSS','≈'],['Next.js','N']];
const projects=[
{name:"Bird's Eye Markets",tag:'Full Stack',desc:'Property intelligence platform combining ownership, valuation, rental and market data.',tech:['Next.js','Node.js','Python','Supabase']},
{name:'Queflic',tag:'Mobile',desc:'Social mobile application with profiles, feeds, photo/video posts and live moments.',tech:['React Native','Node.js','MongoDB']},
{name:'Paradise Rental',tag:'Full Stack',desc:'Property rental marketplace for browsing listings, booking stays and managing accounts.',tech:['React','Node.js','MySQL']},
{name:'QuickKart',tag:'MERN',desc:'E-commerce product with catalog, cart, authentication, checkout and order history.',tech:['React','Express','MongoDB']},
{name:'Informed.pro',tag:'Product',desc:'Professional network with profiles, connections, feeds and data-heavy dashboards.',tech:['React','Redux','Node.js']},
{name:'Docintel',tag:'AI',desc:'Clinical research application with AI-curated content, saved articles and CPD tracking.',tech:['React','Node.js','MongoDB']}
];
function visitorId(){if(typeof window==='undefined')return '';let id=localStorage.getItem('portfolio_visitor_id');if(!id){id=crypto.randomUUID();localStorage.setItem('portfolio_visitor_id',id)}return id}
async function track(type:string,page=location.pathname){if(!isSupabaseConfigured||!supabase)return;try{await supabase.from('visitor_events').insert({visitor_id:visitorId(),event_type:type,page,referrer:document.referrer||null,user_agent:navigator.userAgent,language:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})}catch{}}
export default function PortfolioReference(){useEffect(()=>{track('page_view');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.12});document.querySelectorAll('.animate-in').forEach(el=>io.observe(el));return()=>io.disconnect()},[]);return <main className="ref-site">
<nav className="ref-nav"><a href="#home" className="ref-logo">VIBHU<span>.</span></a><div className="ref-links"><a href="#home">Home</a><a href="#about">About</a><a href="#skills">Skills</a><a href="#projects">Projects</a><a href="#experience">Experience</a><a href="#contact">Contact</a></div><a className="admin-pill" href="/portfolio/admin/">▢ Admin</a></nav>
<section className="ref-hero" id="home"><div className="hero-copy-ref"><div className="role-pill">&lt;/&gt;&nbsp; FULL STACK DEVELOPER</div><h1>Hi, I’m <span>Vibhu</span></h1><h2>I build modern, responsive and high-performance web applications.</h2><p>Full-Stack Developer focused on solving real-world problems with clean code, reliable APIs, automation and thoughtful product design.</p><div className="hero-buttons"><a href="#projects" className="purple-btn">View My Work →</a><a href="/portfolio/resume.pdf" className="dark-btn" onClick={()=>track('resume_download')}>Download Resume ↓</a></div><div className="social-row"><span>Let’s connect:</span><a href="https://www.linkedin.com" target="_blank">in</a><a href="https://github.com/vibhu10" target="_blank">◎</a><a href="mailto:kumar.vibhu.id@gmail.com" onClick={()=>track('contact_click')}>✉</a></div></div><div className="profile-panel"><div className="profile-orbit"><div className="avatar-placeholder"><span>KV</span></div><i/></div><h3>Vibhu</h3><p>Full Stack Developer</p><small>⌖ India</small><a href="/portfolio/resume.pdf" onClick={()=>track('resume_download')}>Download Resume ↓</a></div></section>
<div className="stat-strip animate-in"><div><b>⌁</b><strong>6+</strong><span>Projects Completed</span></div><div><b>◌</b><strong>3+</strong><span>Years Experience</span></div><div><b>♜</b><strong>20+</strong><span>Technologies</span></div><div><b>↗</b><strong>100%</strong><span>Ownership Mindset</span></div></div>
<section className="ref-two-col animate-in" id="about"><div><label>ABOUT ME</label><h2>Who I Am</h2><p>I’m a Full-Stack Developer building production web applications with modern technologies. I enjoy turning ideas into real products with responsive interfaces, scalable APIs and practical automation.</p><p>I specialize in React, Next.js, Node.js, JavaScript/TypeScript, Python and data-driven applications.</p><a className="outline-btn" href="#experience">◉ More About Me</a></div><div id="skills"><label>SKILLS</label><h2>My Technical Skills</h2><div className="skill-icon-grid">{skills.map(([n,i])=><div className="skill-icon" key={n}><b>{i}</b><span>{n}</span></div>)}</div></div></section>
<section className="animate-in" id="projects"><div className="section-head-ref"><div><label>PROJECTS</label><h2>My Recent Work</h2></div><span className="outline-btn">Selected Projects ›</span></div><div className="ref-project-grid">{projects.map((p,i)=><article className="ref-project" key={p.name}><div className={`project-art art-${i+1}`}><span>{String(i+1).padStart(2,'0')}</span><b>{p.name}</b></div><div className="project-body"><h3>{p.name}</h3><em>{p.tag}</em><p>{p.desc}</p><div>{p.tech.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div></section>
<section className="ref-bottom animate-in" id="experience"><div><label>EXPERIENCE</label><h2>Work Experience</h2><div className="timeline-ref"><article><i/><div><b>Full-Stack Developer</b><span>2024 – Present</span><small>WebNext Technologies · Mohali</small><p>Building production applications, APIs, data pipelines, automations and cloud infrastructure.</p></div></article><article><i/><div><b>MERN Stack Developer</b><span>2022 – 2024</span><small>ShineDezign · Mohali</small><p>Built full-stack features, dashboards, authentication, APIs and data-heavy product experiences.</p></div></article></div></div><div id="contact"><label>CONTACT</label><h2>Let’s Connect</h2><p>I’m currently open to new full-stack and product engineering opportunities. Feel free to reach out.</p><ul><li>✉ kumar.vibhu.id@gmail.com</li><li>⌖ India · Remote</li><li>◎ github.com/vibhu10</li></ul><a className="purple-btn" href="mailto:kumar.vibhu.id@gmail.com" onClick={()=>track('contact_click')}>Send Message ↗</a></div></section>
<footer className="ref-footer"><b>VIBHU<span>.</span></b><small>© 2026 Vibhu. Built with Next.js.</small><div><a href="#home">Home</a><a href="#projects">Projects</a><a href="#contact">Contact</a></div></footer>
</main>}
