'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {supabase,isSupabaseConfigured} from '../lib/supabase';

type CmsProject={id?:string;name:string;category:string;summary:string;impact:string;role:string[];tech:string[];screenshots?:string[];live_url?:string;github_url?:string;featured?:boolean;visible?:boolean;sort_order?:number};
type CmsSkill={id?:string;category:string;name:string;sort_order?:number;visible?:boolean};
type Project={name:string;type:string;desc:string;purpose:string;impact:string;tech:string[];built:string[];screenshots?:string[];live?:string;github?:string};
type Experience={id?:string;title:string;company:string;location:string;start_date:string;end_date:string;description:string;skills:string[];visible?:boolean;sort_order?:number};
type SiteContent={display_name:string;short_name:string;headline:string;hero_text:string;role_title:string;location:string;email:string;phone:string;github_url:string;linkedin_url:string;portfolio_url:string;about_one:string;about_two:string;contact_heading:string;contact_text:string;experience_years:string;footer_text:string};
const BASE='/portfolio';
const defaultSite:SiteContent={display_name:'Kumar Vibhu',short_name:'Vibhu',headline:'I build modern, responsive and high-performance web products.',hero_text:'Full-Stack Developer focused on production-ready applications, APIs, automation and data-driven platforms — from interface to infrastructure.',role_title:'Full-Stack Developer',location:'India · Remote',email:'kumar.vibhu.id@gmail.com',phone:'+91 98163 99109',github_url:'https://github.com/vibhu10',linkedin_url:'',portfolio_url:'https://vibhu10.github.io/portfolio/',about_one:'I build production web applications and enjoy owning the complete engineering flow: translating requirements into interfaces, designing APIs and data models, integrating external services, automating repetitive work and shipping applications to the cloud.',about_two:'My strongest stack is JavaScript/TypeScript with React, Next.js and Node.js, plus Python/FastAPI, browser automation and modern databases when the product needs them.',contact_heading:'Let’s build something useful.',contact_text:'I’m open to full-stack, React/Next.js and product engineering opportunities.',experience_years:'3+',footer_text:'© 2026 Kumar Vibhu · Built with Next.js + Supabase'};
const fallbackExperiences:Experience[]=[{title:'Full-Stack Developer',company:'WebNext Technologies',location:'Mohali',start_date:'Feb 2024',end_date:'Present',description:'Building production applications, APIs, data pipelines, automation and cloud infrastructure, including Bird’s Eye Markets.',skills:['Next.js','Node.js','Python','Supabase','Docker']},{title:'MERN Stack Developer',company:'ShineDezign',location:'Mohali',start_date:'Dec 2022',end_date:'Jan 2024',description:'Built full-stack product features, dashboards, authentication, APIs and data-heavy application experiences.',skills:['React','Node.js','Express.js','MongoDB']}];
const fallbackProjects:Project[]=[
{name:"Bird's Eye Markets",type:'REAL ESTATE INTELLIGENCE · PRODUCTION SAAS',desc:'A property intelligence platform that combines ownership, valuation, rental, demographic and market data into structured reports and decision-ready dashboards.',purpose:'Built to help real-estate users research properties faster and turn fragmented data into one usable workflow.',impact:'Worked across frontend, backend, data enrichment, automation and deployment for a production SaaS product.',tech:['Next.js 14','React 18','TypeScript','Tailwind CSS','Chakra UI','Node.js','Express.js','Python','FastAPI','Supabase','PostgreSQL','Playwright','n8n','Docker','Docker Compose','Nginx','DigitalOcean','Stripe'],built:['Built the full Next.js frontend for property search, reports and market-analysis dashboards.','Designed Node.js/Express REST APIs plus supporting Python/FastAPI services for report generation and data aggregation.','Built Python/Playwright scraping and browser-automation workflows integrating ATTOM, AirROI, Zillow, Realtor, Google Maps and analytics data.','Automated recurring data-processing jobs with n8n and webhooks.','Containerized services with Docker/Docker Compose and deployed on DigitalOcean behind Nginx.','Integrated Stripe billing and managed production credentials and deployment workflows.']},
{name:'Queflic',type:'SOCIAL MEDIA · MOBILE APPLICATION',desc:'A social mobile application with profiles, feeds, photo/video posts and a differentiating live-photo-moment format that combines a photo with a short video clip.',purpose:'Designed to give users a modern social experience around sharing media, following people and discovering activity from their network.',impact:'Owned the backend and contributed to the React Native application, including data models and media-processing workflows.',tech:['React Native','Node.js','Express.js','MongoDB','REST APIs'],built:['Designed REST APIs for users, profiles, feeds, posts and media uploads.','Created MongoDB models for social relationships and content.','Built the media pipeline that processes and stores combined photo/video moments.','Contributed to React Native screens and cross-platform mobile flows.']},
{name:'Paradise Rental',type:'PROPERTY RENTAL MARKETPLACE',desc:'A property-rental marketplace where users browse listings, view details, book stays and manage renter or property-owner accounts.',purpose:'Built to simplify the journey from property discovery to booking and transaction handling in one responsive marketplace.',impact:'Led development end-to-end across the customer-facing marketplace and backend services.',tech:['React.js','Node.js','Express.js','MongoDB','MySQL','REST APIs','JWT Authentication'],built:['Built responsive React listing, detail and booking flows.','Developed Node.js/Express APIs for listings, bookings and authentication.','Modeled and integrated MongoDB/MySQL for property, booking and user data.','Implemented JWT authentication and protected account workflows.']},
{name:'QuickKart',type:'E-COMMERCE · MERN',desc:'A full e-commerce storefront covering product browsing, cart, checkout, authentication and order history.',purpose:'Built as a complete shopping experience connecting responsive storefront interactions with reliable backend APIs and order processing.',impact:'Owned the core MERN product flow from UI to API and database.',tech:['React.js','Node.js','Express.js','MongoDB','JWT','REST APIs'],built:['Built responsive product listing, cart and checkout experiences.','Developed product, user and order APIs.','Modeled product, user and order data in MongoDB.','Implemented JWT authentication and checkout/payment workflows.']},
{name:'Informed.pro',type:'PROFESSIONAL NETWORK',desc:'A professional networking product with structured profiles, connections, activity feeds and role-aware dashboards.',purpose:'Created to support professional discovery and engagement through profile data and network activity.',impact:'Focused on data-heavy UX, performance and access-controlled product experiences.',tech:['React.js','Redux','Node.js','Express.js','MongoDB'],built:['Built profile, feed and dashboard features.','Implemented authentication and role-based access.','Improved large-list performance using pagination and MongoDB indexing.','Integrated frontend state with backend APIs using Redux.']},
{name:'Docintel',type:'AI · CLINICAL RESEARCH',desc:'A clinical research application with AI-curated content, saved articles and CPD tracking.',purpose:'Built to help professionals discover relevant research and keep track of learning activity in one product.',impact:'Connected research-discovery UX, user workflows and backend APIs.',tech:['React.js','Node.js','Express.js','MongoDB','REST APIs'],built:['Built AI-curated research feed experiences.','Implemented saved articles and CPD tracking.','Developed REST APIs for content and user actions.','Created reusable responsive frontend components.']}
];
const fallbackSkills=['HTML5','CSS3','JavaScript','TypeScript','React','Next.js','Node.js','Express.js','Python','FastAPI','MongoDB','PostgreSQL','Supabase','Docker','Playwright','n8n'];
const devicon:Record<string,string>={'HTML5':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg','HTML':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg','CSS3':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg','CSS':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg','JavaScript':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg','TypeScript':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg','React':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg','React.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg','Next.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg','Node.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg','Express.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg','Express':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg','Python':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg','FastAPI':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fastapi/fastapi-original.svg','MongoDB':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg','PostgreSQL':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg','Supabase':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/supabase/supabase-original.svg','Docker':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg','Playwright':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/playwright/playwright-original.svg','n8n':'https://cdn.simpleicons.org/n8n/EA4B71'};
function visitorId(){if(typeof window==='undefined')return '';let id=localStorage.getItem('portfolio_visitor_id');if(!id){id=crypto.randomUUID();localStorage.setItem('portfolio_visitor_id',id)}return id}
async function track(type:string,page?:string){if(!isSupabaseConfigured||!supabase||typeof window==='undefined')return;await supabase.from('visitor_events').insert({visitor_id:visitorId(),event_type:type,page:page||location.pathname,referrer:document.referrer||null,user_agent:navigator.userAgent,language:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})}
const Icon=({name}:{name:'code'|'briefcase'|'stack'|'rocket'|'mail'|'pin'|'github'|'download'})=>{const common={width:20,height:20,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};if(name==='code')return <svg {...common}><path d='m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14'/></svg>;if(name==='briefcase')return <svg {...common}><rect x='3' y='7' width='18' height='12' rx='2'/><path d='M8 7V5h8v2M3 12h18'/></svg>;if(name==='stack')return <svg {...common}><path d='m12 3 9 5-9 5-9-5 9-5Z'/><path d='m3 12 9 5 9-5M3 16l9 5 9-5'/></svg>;if(name==='rocket')return <svg {...common}><path d='M14 5c3-3 5-2 5-2s1 2-2 5l-6 6-5-1-1-5 6-6Z'/><path d='m9 15-4 4M5 14l-2 5 5-2'/></svg>;if(name==='mail')return <svg {...common}><rect x='3' y='5' width='18' height='14' rx='2'/><path d='m3 7 9 6 9-6'/></svg>;if(name==='pin')return <svg {...common}><path d='M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z'/><circle cx='12' cy='10' r='2.3'/></svg>;if(name==='github')return <svg {...common}><path d='M15 22v-4a4.8 4.8 0 0 0-1-3.5c3.3-.4 6.8-1.6 6.8-7A5.5 5.5 0 0 0 19.3 4 5 5 0 0 0 19.1.5S17.9.1 15 2a13.4 13.4 0 0 0-7 0C5.1.1 3.9.5 3.9.5A5 5 0 0 0 3.7 4a5.5 5.5 0 0 0-1.5 3.8c0 5.4 3.5 6.6 6.8 7A4.8 4.8 0 0 0 8 18v4'/><path d='M8 19c-3 .9-3-1.5-4-2'/></svg>;return <svg {...common}><path d='M12 3v12M7 10l5 5 5-5M5 21h14'/></svg>};
function mapProject(p:CmsProject):Project{return{name:p.name,type:p.category||'FULL-STACK PRODUCT',desc:p.summary,purpose:p.summary,impact:p.impact,tech:p.tech||[],built:p.role||[],screenshots:p.screenshots||[],live:p.live_url||'',github:p.github_url||''}}

export default function PortfolioReference(){
 const[projects,setProjects]=useState<Project[]>(fallbackProjects),[skills,setSkills]=useState<string[]>(fallbackSkills),[experiences,setExperiences]=useState<Experience[]>(fallbackExperiences),[profile,setProfile]=useState(`${BASE}/profile-320.jpg`),[resume,setResume]=useState(`${BASE}/resume.pdf`),[site,setSite]=useState<SiteContent>(defaultSite);
 const[contact,setContact]=useState({name:'',email:'',subject:'',message:''}),[sending,setSending]=useState(false),[contactStatus,setContactStatus]=useState('');
 useEffect(()=>{track('page_view');const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('show')),{threshold:.1});document.querySelectorAll('.v2-reveal').forEach(x=>io.observe(x));if(supabase&&isSupabaseConfigured){(async()=>{const[p,s,assets,c,x]=await Promise.all([supabase.from('projects').select('*').eq('visible',true).order('sort_order'),supabase.from('skills').select('*').eq('visible',true).order('sort_order'),supabase.storage.from('portfolio').list('site'),supabase.from('site_content').select('*').eq('id',1).maybeSingle(),supabase.from('experiences').select('*').eq('visible',true).order('sort_order')]);if(p.data?.length)setProjects((p.data as CmsProject[]).map(mapProject));if(s.data?.length)setSkills((s.data as CmsSkill[]).map(v=>v.name));if(c.data)setSite({...defaultSite,...c.data});if(x.data?.length)setExperiences(x.data as Experience[]);if(assets.data){const names=new Set(assets.data.map(v=>v.name));if(names.has('profile.jpg'))setProfile(supabase.storage.from('portfolio').getPublicUrl('site/profile.jpg').data.publicUrl);if(names.has('resume.pdf'))setResume(supabase.storage.from('portfolio').getPublicUrl('site/resume.pdf').data.publicUrl)}})()}return()=>io.disconnect()},[]);
 const allTech=useMemo(()=>skills.length?skills:fallbackSkills,[skills]);const mail=`mailto:${site.email}`;
 const sendMessage=async(e:FormEvent)=>{e.preventDefault();setContactStatus('');if(!supabase){setContactStatus('Messaging is temporarily unavailable. Please email me directly.');return}setSending(true);const{error}=await supabase.from('contact_messages').insert({name:contact.name.trim(),email:contact.email.trim(),subject:contact.subject.trim(),message:contact.message.trim(),status:'unread'});if(error)setContactStatus('Could not send from the form yet. Please use the email link above.');else{setContactStatus('Message sent successfully. I’ll get back to you soon.');setContact({name:'',email:'',subject:'',message:''});track('contact_message')}setSending(false)};
 return <main className='portfolio-v2'>
<nav className='v2-nav'><a href='#home' className='v2-logo'>{site.short_name.toUpperCase()}<span>.</span></a><div className='v2-links'><a href='#about'>About</a><a href='#skills'>Skills</a><a href='#projects'>Projects</a><a href='#experience'>Experience</a><a href='#contact'>Contact</a></div><a className='v2-admin' href={`${BASE}/admin/`}>Admin Panel ↗</a></nav>
<header className='v2-hero' id='home'><div className='v2-glow one'/><div className='v2-copy'><div className='v2-pill'><Icon name='code'/> {site.role_title.toUpperCase()}</div><h1>Hi, I’m <span>{site.short_name}.</span></h1><h2>{site.headline}</h2><p>{site.hero_text}</p><div className='v2-actions'><a className='v2-primary' href='#projects'>View My Work <span>→</span></a><a className='v2-secondary' href={resume} target='_blank' rel='noreferrer' onClick={()=>track('resume_download')}><Icon name='download'/> Download Resume</a></div><div className='v2-social'><span>Let’s connect</span><a href={site.github_url} target='_blank' aria-label='GitHub'><Icon name='github'/></a><a href={mail} onClick={()=>track('contact_click')} aria-label='Email'><Icon name='mail'/></a></div></div><aside className='v2-profile'><div className='v2-avatar-wrap'><div className='v2-ring r1'/><div className='v2-ring r2'/><img src={profile} alt={site.display_name} onError={e=>{e.currentTarget.src=`${BASE}/profile-320.jpg`}}/><i/></div><h3>{site.display_name}</h3><p>{site.role_title}</p><small><Icon name='pin'/> {site.location}</small><div className='v2-profile-tags'><span>React</span><span>Next.js</span><span>Node.js</span></div></aside></header>
<section className='v2-stats v2-reveal'><div><span className='stat-icon'><Icon name='briefcase'/></span><b>{projects.length}+</b><small>Featured Projects</small></div><div><span className='stat-icon'><Icon name='stack'/></span><b>{site.experience_years}</b><small>Years Building Products</small></div><div><span className='stat-icon'><Icon name='code'/></span><b>{allTech.length}+</b><small>Technologies</small></div><div><span className='stat-icon'><Icon name='rocket'/></span><b>Full Stack</b><small>UI → API → Data → Deploy</small></div></section>
<section className='v2-about v2-reveal' id='about'><div><label>ABOUT ME</label><h2>Who I Am</h2><p>{site.about_one}</p><p>{site.about_two}</p></div><div id='skills'><label>TECH STACK</label><h2>Tools I Work With</h2><div className='v2-skill-grid'>{allTech.map(n=><div className='v2-skill brand-skill' key={n}>{devicon[n]?<img src={devicon[n]} alt=''/>:<b>{n.slice(0,2).toUpperCase()}</b>}<span>{n}</span></div>)}</div></div></section>
<section className='v2-projects v2-reveal' id='projects'><div className='v2-section-head'><div><label>SELECTED WORK</label><h2>Projects with real product depth.</h2></div><p>Each project shows what the product was built for, the technologies used and the engineering work I contributed.</p></div><div className='v2-project-grid'>{projects.map((p,i)=><article className={'v2-project '+(i===0?'featured':'')} key={p.name}><div className='v2-project-art'>{p.screenshots?.[0]?<img src={p.screenshots[0]} alt={`${p.name} screenshot`}/>:<><span>0{i+1}</span><div className='art-lines'/></>}<b>{p.name}</b><small>{p.type}</small></div><div className='v2-project-body'><h3>{p.name}</h3><p className='v2-desc'>{p.desc}</p><div className='v2-purpose'><b>What it is for</b><p>{p.purpose}</p></div><div className='v2-impact'><b>My role</b><p>{p.impact}</p></div><div className='v2-tech'>{p.tech.map(t=><span key={t}>{t}</span>)}</div><details onToggle={e=>e.currentTarget.open&&track('project_open','#'+p.name)}><summary>View full contribution <span>+</span></summary><ul>{p.built.map(x=><li key={x}>{x}</li>)}</ul>{(p.live||p.github)&&<div className='project-links'>{p.live&&<a href={p.live} target='_blank'>Live site ↗</a>}{p.github&&<a href={p.github} target='_blank'>GitHub ↗</a>}</div>}</details></div></article>)}</div></section>
<section className='v2-bottom v2-reveal' id='experience'><div className='experience-public'><label>EXPERIENCE</label><h2>Where I’ve built.</h2><div className='v2-timeline'>{experiences.map((x,i)=><article key={x.id||`${x.company}-${i}`}><i/><div><b>{x.title}</b><span>{x.start_date} — {x.end_date}</span><small>{x.company}{x.location?` · ${x.location}`:''}</small><p>{x.description}</p>{x.skills?.length>0&&<div className='experience-tags'>{x.skills.map(s=><em key={s}>{s}</em>)}</div>}</div></article>)}</div></div><div id='contact' className='v2-contact'><label>CONTACT</label><h2>{site.contact_heading}</h2><p>{site.contact_text}</p><a href={mail} onClick={()=>track('contact_click')}><Icon name='mail'/><span><small>Email me</small><b>{site.email}</b></span></a><a href={site.github_url} target='_blank'><Icon name='github'/><span><small>GitHub</small><b>{site.github_url.replace(/^https?:\/\//,'')}</b></span></a>{site.phone&&<a href={`tel:${site.phone.replace(/\s/g,'')}`}><Icon name='pin'/><span><small>Phone</small><b>{site.phone}</b></span></a>}<div className='contact-form-box'><h3>Send me a message</h3><p>Use the form below and your message will arrive directly in my portfolio admin inbox.</p><form onSubmit={sendMessage}><div className='contact-form-row'><input required placeholder='Your name' value={contact.name} onChange={e=>setContact({...contact,name:e.target.value})}/><input required type='email' placeholder='Email address' value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></div><input placeholder='Subject' value={contact.subject} onChange={e=>setContact({...contact,subject:e.target.value})}/><textarea required minLength={5} rows={5} placeholder='Tell me about the opportunity or project…' value={contact.message} onChange={e=>setContact({...contact,message:e.target.value})}/><button className='v2-primary contact-btn' disabled={sending}>{sending?'Sending…':'Send Message →'}</button>{contactStatus&&<small className='contact-status'>{contactStatus}</small>}</form></div></div></section>
<footer className='v2-footer'><b>{site.short_name.toUpperCase()}<span>.</span></b><small>{site.footer_text}</small><a href='#home'>Back to top ↑</a></footer>
</main>}
