'use client';

import {FormEvent,useEffect,useState} from 'react';
import {supabase,isSupabaseConfigured} from '../lib/supabase';

type Exp={id:string;title:string;company:string;location:string;start_date:string;end_date:string;description:string;skills:string[]};
type Content={display_name:string;email:string;github_url:string;contact_heading:string;contact_text:string;footer_text:string};
const fallbackExp:Exp[]=[{id:'1',title:'Full-Stack Developer',company:'WebNext Technologies',location:'Mohali',start_date:'Feb 2024',end_date:'Present',description:'Building production applications, APIs, data pipelines, automation and cloud infrastructure, including Bird’s Eye Markets.',skills:['Next.js','Node.js','Python','Supabase','Docker']},{id:'2',title:'MERN Stack Developer',company:'ShineDezign',location:'Mohali',start_date:'Dec 2022',end_date:'Jan 2024',description:'Built full-stack product features, dashboards, authentication, APIs and data-heavy application experiences.',skills:['React','Node.js','Express.js','MongoDB']}];
const fallbackContent:Content={display_name:'Kumar Vibhu',email:'kumar.vibhu.id@gmail.com',github_url:'https://github.com/vibhu10',contact_heading:'Let’s build something useful.',contact_text:'I’m open to full-stack, React/Next.js and product engineering opportunities.',footer_text:'© 2026 Kumar Vibhu · Built with Next.js + Supabase'};

export default function PortfolioExtras(){
 const[experiences,setExperiences]=useState<Exp[]>(fallbackExp),[content,setContent]=useState<Content>(fallbackContent),[name,setName]=useState(''),[email,setEmail]=useState(''),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[err,setErr]=useState('');
 useEffect(()=>{if(!supabase||!isSupabaseConfigured)return;(async()=>{const[e,c]=await Promise.all([supabase.from('experiences').select('*').eq('visible',true).order('sort_order'),supabase.from('site_content').select('display_name,email,github_url,contact_heading,contact_text,footer_text').eq('id',1).maybeSingle()]);if(e.data?.length)setExperiences(e.data as Exp[]);if(c.data)setContent({...fallbackContent,...c.data})})()},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setErr('');setSent(false);if(!supabase){setErr('Message service is unavailable right now.');return}setBusy(true);const{error}=await supabase.from('contact_messages').insert({name:name.trim(),email:email.trim(),subject:subject.trim(),message:message.trim(),status:'unread'});if(error)setErr(error.message);else{setSent(true);setName('');setEmail('');setSubject('');setMessage('');await supabase.from('visitor_events').insert({visitor_id:localStorage.getItem('portfolio_visitor_id')||crypto.randomUUID(),event_type:'contact_message',page:location.pathname,referrer:document.referrer||null,user_agent:navigator.userAgent,language:navigator.language,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})}setBusy(false)};
 return <><style>{`.portfolio-v2>.v2-bottom,.portfolio-v2>.v2-footer{display:none}.portfolio-extras{background:#080a0d;color:#edf1f5}.contact-form{margin-top:22px;display:grid;gap:11px}.contact-form .two{display:grid;grid-template-columns:1fr 1fr;gap:10px}.contact-form input,.contact-form textarea{width:100%;border:1px solid #2d3540;background:#0a0e12;color:#edf1f5;border-radius:10px;padding:12px;font:13px inherit;outline:none}.contact-form input:focus,.contact-form textarea:focus{border-color:#b8f36b}.contact-form button{border:0;border-radius:9px;background:#b8f36b;color:#0a0e08;font-weight:800;padding:13px;cursor:pointer}.contact-form small{color:#7d8994}.contact-ok{color:#9fe56a}.contact-error{color:#ff9c9c}.exp-tags{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.exp-tags span{font-size:10px;border:1px solid #303941;border-radius:999px;padding:4px 7px;color:#9ba7b1}@media(max-width:620px){.contact-form .two{grid-template-columns:1fr}}`}</style><div className="portfolio-v2 portfolio-extras"><section className='v2-bottom v2-reveal show' id='experience'><div><label>EXPERIENCE</label><h2>Where I’ve built.</h2><div className='v2-timeline'>{experiences.map(x=><article key={x.id}><i/><div><b>{x.title}</b><span>{x.start_date} — {x.end_date}</span><small>{x.company}{x.location?` · ${x.location}`:''}</small><p>{x.description}</p>{x.skills?.length>0&&<div className="exp-tags">{x.skills.map(s=><span key={s}>{s}</span>)}</div>}</div></article>)}</div></div><div id='contact' className='v2-contact'><label>CONTACT</label><h2>{content.contact_heading}</h2><p>{content.contact_text}</p><a href={`mailto:${content.email}`}><span><small>Email me</small><b>{content.email}</b></span></a><a href={content.github_url} target='_blank'><span><small>GitHub</small><b>{content.github_url.replace('https://','')}</b></span></a><form className="contact-form" onSubmit={submit}><div className="two"><input placeholder="Your name" value={name} onChange={e=>setName(e.target.value)} required minLength={2}/><input type="email" placeholder="Your email" value={email} onChange={e=>setEmail(e.target.value)} required/></div><input placeholder="Subject" value={subject} onChange={e=>setSubject(e.target.value)}/><textarea rows={5} placeholder="Write your message..." value={message} onChange={e=>setMessage(e.target.value)} required minLength={5}/>{sent&&<small className="contact-ok">Message sent. I’ll get it in my portfolio admin inbox.</small>}{err&&<small className="contact-error">{err}</small>}<button disabled={busy}>{busy?'Sending…':'Send message →'}</button></form></div></section><footer className='v2-footer'><b>VIBHU<span>.</span></b><small>{content.footer_text}</small><a href='#home'>Back to top ↑</a></footer></div></>
}
