'use client';

import {useEffect,useMemo,useState} from 'react';
import {createPortal} from 'react-dom';
import {supabase,isSupabaseConfigured} from '../lib/supabase';

type Skill={id?:string;category:string;name:string;sort_order?:number;visible?:boolean};

const confirmed:Skill[]=[
 {name:'HTML5',category:'Tech: Frontend'},{name:'CSS3',category:'Tech: Frontend'},{name:'JavaScript',category:'Tech: Frontend'},{name:'TypeScript',category:'Tech: Frontend'},{name:'React',category:'Tech: Frontend'},{name:'React Native',category:'Tech: Mobile'},{name:'Next.js',category:'Tech: Frontend'},{name:'Tailwind CSS',category:'Tech: Frontend'},{name:'Chakra UI',category:'Tech: Frontend'},{name:'Redux',category:'Tech: Frontend'},
 {name:'Node.js',category:'Tech: Backend'},{name:'Express.js',category:'Tech: Backend'},{name:'Python',category:'Tech: Backend'},{name:'FastAPI',category:'Tech: Backend'},{name:'REST API',category:'Tech: APIs'},{name:'JWT',category:'Tech: Authentication'},{name:'OAuth',category:'Tech: Authentication'},{name:'WebSockets',category:'Tech: APIs'},
 {name:'MongoDB',category:'Tech: Data'},{name:'PostgreSQL',category:'Tech: Data'},{name:'MySQL',category:'Tech: Data'},{name:'Redis',category:'Tech: Data'},
 {name:'OpenAI API',category:'Tech: AI'},{name:'LLM APIs',category:'Tech: AI'},{name:'Embeddings',category:'Tech: AI'},{name:'RAG',category:'Tech: AI'},{name:'Vector Databases',category:'Tech: AI'},{name:'AI Agents',category:'Tech: AI'},
 {name:'VS Code',category:'Tool: Editor'},{name:'Git',category:'Tool: Version Control'},{name:'GitHub',category:'Tool: Version Control'},{name:'Postman',category:'Tool: API & Testing'},{name:'Playwright',category:'Tool: API & Testing'},{name:'Jest',category:'Tool: API & Testing'},{name:'Vitest',category:'Tool: API & Testing'},
 {name:'npm',category:'Tool: Package & Build'},{name:'pnpm',category:'Tool: Package & Build'},{name:'Chrome DevTools',category:'Tool: Editor'},{name:'Docker',category:'Tool: DevOps & Cloud'},{name:'Docker Compose',category:'Tool: DevOps & Cloud'},{name:'Nginx',category:'Tool: DevOps & Cloud'},{name:'GitHub Actions',category:'Tool: DevOps & Cloud'},{name:'AWS',category:'Tool: DevOps & Cloud'},{name:'DigitalOcean',category:'Tool: DevOps & Cloud'},{name:'Vercel',category:'Tool: DevOps & Cloud'},
 {name:'Supabase',category:'Tool: Platforms'},{name:'Stripe',category:'Tool: Platforms'},{name:'n8n',category:'Tool: Automation'},{name:'Figma',category:'Tool: Design & Collaboration'},{name:'Jira',category:'Tool: Design & Collaboration'}
];

const icons:Record<string,string>={
 'HTML5':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg','CSS3':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg','JavaScript':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg','TypeScript':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg','React':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg','React Native':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg','Next.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nextjs/nextjs-original.svg','Tailwind CSS':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg','Chakra UI':'https://cdn.simpleicons.org/chakraui/319795','Redux':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/redux/redux-original.svg','Node.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg','Express.js':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg','Python':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg','FastAPI':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/fastapi/fastapi-original.svg',
 'REST API':'https://cdn.simpleicons.org/swagger/85EA2D','JWT':'https://cdn.simpleicons.org/jsonwebtokens/FFFFFF','OAuth':'https://cdn.simpleicons.org/auth0/EB5424','WebSockets':'https://cdn.simpleicons.org/socketdotio/FFFFFF',
 'MongoDB':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg','PostgreSQL':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg','MySQL':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg','Redis':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/redis/redis-original.svg',
 'OpenAI API':'https://cdn.simpleicons.org/openai/FFFFFF','LLM APIs':'https://cdn.simpleicons.org/openai/FFFFFF','Embeddings':'https://cdn.simpleicons.org/openai/FFFFFF','RAG':'https://cdn.simpleicons.org/openai/FFFFFF','Vector Databases':'https://cdn.simpleicons.org/qdrant/DC244C','AI Agents':'https://cdn.simpleicons.org/openai/FFFFFF',
 'VS Code':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg','Git':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg','GitHub':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg','Postman':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postman/postman-original.svg','Playwright':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/playwright/playwright-original.svg','Jest':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jest/jest-plain.svg','Vitest':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitest/vitest-original.svg','npm':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/npm/npm-original-wordmark.svg','pnpm':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/pnpm/pnpm-original.svg','Chrome DevTools':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/chrome/chrome-original.svg','Docker':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg','Docker Compose':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg','Nginx':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nginx/nginx-original.svg','GitHub Actions':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/githubactions/githubactions-original.svg','AWS':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg','DigitalOcean':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/digitalocean/digitalocean-original.svg','Vercel':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vercel/vercel-original.svg','Supabase':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/supabase/supabase-original.svg','Stripe':'https://cdn.simpleicons.org/stripe/635BFF','n8n':'https://cdn.simpleicons.org/n8n/EA4B71','Figma':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg','Jira':'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jira/jira-original.svg'};

const toolNames=new Set(confirmed.filter(x=>x.category.startsWith('Tool:')).map(x=>x.name));
function isTool(x:Skill){return x.category?.startsWith('Tool:')||toolNames.has(x.name)}
function mergeConfirmed(data:Skill[]){const map=new Map<string,Skill>();for(const x of confirmed)map.set(x.name.toLowerCase(),x);for(const x of data)map.set(x.name.toLowerCase(),x);return [...map.values()].filter(x=>x.visible!==false)}

export default function TechnologyToolsPortal(){
 const[items,setItems]=useState<Skill[]>(confirmed),[target,setTarget]=useState<HTMLElement|null>(null);
 useEffect(()=>{setTarget(document.getElementById('skills'));if(!supabase||!isSupabaseConfigured)return;(async()=>{const{data}=await supabase.from('skills').select('*').eq('visible',true).order('sort_order');if(data)setItems(mergeConfirmed(data as Skill[]))})()},[]);
 const technologies=useMemo(()=>items.filter(x=>!isTool(x)),[items]);
 const tools=useMemo(()=>items.filter(isTool),[items]);
 useEffect(()=>{const stat=document.querySelector('.v2-stats > div:nth-child(3) b');if(stat)stat.textContent=`${technologies.length}+`;const label=document.querySelector('.v2-stats > div:nth-child(3) small');if(label)label.textContent='Technologies'},[technologies.length]);
 if(!target)return null;
 const Card=({x}:{x:Skill})=><div className='v2-skill brand-skill' key={x.id||x.name}>{icons[x.name]?<><img src={icons[x.name]} alt={`${x.name} logo`} onError={e=>{e.currentTarget.style.display='none';const fallback=e.currentTarget.nextElementSibling as HTMLElement|null;if(fallback)fallback.style.display='grid'}}/><b className='skill-icon-fallback' style={{display:'none'}}>{x.name.slice(0,2).toUpperCase()}</b></>:<b>{x.name.slice(0,2).toUpperCase()}</b>}<span>{x.name}</span></div>;
 return createPortal(<><style>{`.v2-about #skills>label,.v2-about #skills>h2,.v2-about #skills>.v2-skill-grid{display:none!important}.skill-split-head{display:flex;align-items:end;justify-content:space-between;gap:14px;margin-bottom:16px}.skill-divider{height:1px;background:#20272d;margin:26px 0 18px}.skill-kind-title{margin:0 0 4px;font-size:22px}.skill-kind-copy{margin:0 0 13px;color:#86919a;font-size:12px}.skill-count-pills{display:flex;gap:7px;flex-wrap:wrap}.skill-count-pills em{font-style:normal;border:1px solid #2d363e;border-radius:999px;padding:5px 9px;font-size:10px;color:#aab4bc}.skill-icon-fallback{width:32px;height:32px;place-items:center;border-radius:8px;border:1px solid #303941;font-size:10px}@media(max-width:700px){.skill-split-head{align-items:flex-start;flex-direction:column}}`}</style><div className='technology-tools-split'><label>TECH STACK</label><div className='skill-split-head'><div><h2 className='skill-kind-title'>Technologies I work with</h2><p className='skill-kind-copy'>Languages, frameworks, APIs, databases and AI technologies I use to build products.</p></div><div className='skill-count-pills'><em>{technologies.length} technologies</em><em>{tools.length} tools</em></div></div><div className='v2-skill-grid'>{technologies.map(x=><Card key={x.id||x.name} x={x}/>)}</div><div className='skill-divider'/><h2 className='skill-kind-title'>Tools & platforms I use</h2><p className='skill-kind-copy'>Development, testing, CI/CD, cloud, deployment, automation and collaboration tools used in my workflow.</p><div className='v2-skill-grid'>{tools.map(x=><Card key={x.id||x.name} x={x}/>)}</div></div></>,target);
}
