'use client';
import {FormEvent,useEffect,useState} from 'react';
import s from './vishu.module.css';
import {official,papers,questions,prelim,mains,gsPriority,gsatPriority,type Kind,type Q} from './data';
import {ActivityHeatmap,Bookmarks,DailyMission,Flashcards,FocusTimer,QuickNotes,ReviewQueue,localKey,type DailyTasks} from './study-tools';
import {DataVault,ExamCountdown,MasteryMatrix,SevenDayPlan,WeeklyPulse} from './study-insights';
import {supabase} from '../../lib/supabase';
import {loadHasProgress,loadQuestionBank,markRevisionReviewed,saveActivity,saveBookmark,saveMockAttempt,saveQuestionAttempt,saveSettings,saveSyllabusProgress,signInStudyUser,syncSimpleSnapshot,type CloudProgress} from './cloud-sync';

const STORE='vishu-progress-v1';
type View='dashboard'|'planner'|'papers'|'practice'|'mock'|'syllabus'|'revision'|'analytics';
type Progress={
 attempts:number;correct:number;topics:Record<string,{a:number;c:number}>;done:string[];
 mocks:{date:string;kind:string;score:number}[];bookmarks:string[];review:string[];
 notes:string;activity:Record<string,number>;daily:Record<string,DailyTasks>;
 examDate:string;weeklyTarget:number
};
const blank:Progress={attempts:0,correct:0,topics:{},done:[],mocks:[],bookmarks:[],review:[],notes:'',activity:{},daily:{},examDate:'',weeklyTarget:35};
function normalizeProgress(saved:any):Progress{return{...blank,...saved,topics:saved?.topics||{},done:saved?.done||[],mocks:saved?.mocks||[],bookmarks:saved?.bookmarks||[],review:saved?.review||[],activity:saved?.activity||{},daily:saved?.daily||{}}}
function mergeProgress(local:Progress,cloud:CloudProgress):Progress{const topics={...local.topics};for(const[topic,v]of Object.entries(cloud.topics)){const cur=topics[topic];if(!cur||v.a>=cur.a)topics[topic]=v}const activity={...local.activity};for(const[d,n]of Object.entries(cloud.activity))activity[d]=Math.max(activity[d]||0,n);const mocks=[...cloud.mocks,...local.mocks].filter((m,i,a)=>a.findIndex(x=>x.date===m.date&&x.kind===m.kind&&x.score===m.score)===i).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,20);const cloudStatsWin=cloud.attempts>=local.attempts;return{attempts:Math.max(local.attempts,cloud.attempts),correct:cloudStatsWin?cloud.correct:local.correct,topics,done:Array.from(new Set([...local.done,...cloud.done])),mocks,bookmarks:Array.from(new Set([...local.bookmarks,...cloud.bookmarks])),review:Array.from(new Set([...local.review,...cloud.review])),notes:cloud.notes||local.notes,activity,daily:{...local.daily,...cloud.daily},examDate:cloud.hasSettings?cloud.examDate:local.examDate,weeklyTarget:cloud.hasSettings?cloud.weeklyTarget:local.weeklyTarget}}
function hasLocalProgress(p:Progress){return Boolean(p.attempts||p.done.length||p.mocks.length||p.bookmarks.length||p.review.length||p.notes||Object.keys(p.activity).length||p.examDate||p.weeklyTarget!==35)}
const pct=(a:number,b:number)=>a?Math.round(b/a*100):0;
const nav:[View,string,string][]=[['dashboard','Command','⌁'],['planner','Planner','◷'],['papers','Papers','▤'],['practice','Practice','✦'],['mock','Mock','◉'],['syllabus','Syllabus','✓'],['revision','Revision Lab','↺'],['analytics','Analytics','⌁']];

export default function Vishu(){
 const[ready,setReady]=useState(false),[auth,setAuth]=useState(false),[view,setView]=useState<View>('dashboard');
 const[p,setP]=useState<Progress>(blank),[bank,setBank]=useState<Q[]>(questions);
 useEffect(()=>{let mounted=true;async function init(){const {data:{session}}=await supabase.auth.getSession();let local=blank;try{local=normalizeProgress(JSON.parse(localStorage.getItem(STORE)||'{}'))}catch{}let next=local;let loadedBank:Q[]=questions;if(session){const [cloud,cloudBank]=await Promise.all([loadHasProgress(),loadQuestionBank()]);if(cloud){next=mergeProgress(local,cloud);if(!cloud.hasCloudData&&hasLocalProgress(local))void syncSimpleSnapshot(local)}if(cloudBank.length)loadedBank=cloudBank}if(!mounted)return;setAuth(Boolean(session));setP(next);setBank(loadedBank);setReady(true)}init();return()=>{mounted=false}},[]);
 useEffect(()=>{if(ready)localStorage.setItem(STORE,JSON.stringify(p))},[p,ready]);
 useEffect(()=>{if(!ready||!auth)return;const timer=setTimeout(()=>{void saveSettings(p.examDate,p.weeklyTarget,p.notes)},600);return()=>clearTimeout(timer)},[p.examDate,p.weeklyTarget,p.notes,ready,auth]);
 if(!ready)return <main className={s.loading}><div className={s.loader}/><span>Building your study command center…</span></main>;
 if(!auth)return <Login onOk={async()=>{const [cloud,cloudBank]=await Promise.all([loadHasProgress(),loadQuestionBank()]);if(cloud)setP(x=>mergeProgress(x,cloud));if(cloudBank.length)setBank(cloudBank);setAuth(true)}}/>;

 const acc=pct(p.attempts,p.correct),all=[...prelim,...mains],syll=Math.round(p.done.length/all.length*100);
 const weak=Object.entries(p.topics).filter(([,v])=>v.a>=2).map(([topic,v])=>({topic,acc:pct(v.a,v.c),n:v.a})).sort((a,b)=>a.acc-b.acc);
 const readiness=Math.round((acc+syll+(p.mocks[0]?.score||0))/3),streak=calcStreak(p.activity),today=localKey(),todayTasks=p.daily[today]||{};
 const toggleBookmark=(id:string)=>setP(x=>{const saved=!x.bookmarks.includes(id);void saveBookmark(id,saved);return{...x,bookmarks:saved?[...x.bookmarks,id]:x.bookmarks.filter(v=>v!==id)}});
 const addActivity=(amount=1)=>setP(x=>{const count=(x.activity[today]||0)+amount;void saveActivity(today,count,x.daily[today]||{});return{...x,activity:{...x.activity,[today]:count}}});
 const updateDaily=(tasks:DailyTasks)=>setP(x=>{const count=(x.activity[today]||0)+1;void saveActivity(today,count,tasks);return{...x,daily:{...x.daily,[today]:tasks},activity:{...x.activity,[today]:count}}});
 const logout=async()=>{await supabase.auth.signOut();setAuth(false)};

 return <div className={s.app}>
  <div className={s.ambient}><i/><i/><i/><i/></div>
  <aside className={s.side}>
   <div className={s.brand}><div className={s.mark}>H</div><div><strong>HAS Command</strong><small>VISHU STUDY OS</small></div></div>
   <div className={s.profileMini}><div>S</div><span><b>Suyash</b><small>{streak} day streak · {p.review.length} reviews</small></span></div>
   <div className={s.navLabel}>WORKSPACE</div>
   <nav>{nav.map(([id,label,icon])=><button key={id} className={view===id?s.active:''} onClick={()=>setView(id)}><span>{icon}</span><b>{label}</b>{view===id&&<i/>}</button>)}</nav>
   <div className={s.sideCard}><div><span>Overall progress</span><b>{syll}%</b></div><div className={s.bar}><i style={{width:syll+'%'}}/></div><small>{p.done.length}/{all.length} syllabus blocks complete</small></div>
   <button className={s.lock} onClick={logout}>↗ Logout</button>
  </aside>

  <main className={s.main}>
   <header className={s.topbar}><div><small>HIMACHAL PRADESH ADMINISTRATIVE SERVICE</small><h1>{title(view)}</h1></div><div className={s.topActions}><button className={s.quickBtn} onClick={()=>setView('practice')}>✦ Quick 5</button><div className={s.live}><i/> Study OS online</div><button className={s.logoutTop} onClick={logout}>Logout ↗</button><a href={official.home} target="_blank">HPPSC ↗</a></div></header>
   <div className={s.content}>
    {view==='dashboard'&&<Dashboard p={p} acc={acc} syll={syll} weak={weak} readiness={readiness} streak={streak} setView={setView} setExamDate={examDate=>setP(x=>({...x,examDate}))} setWeeklyTarget={weeklyTarget=>setP(x=>({...x,weeklyTarget}))}/>}
    {view==='planner'&&<Planner p={p} tasks={todayTasks} setTasks={updateDaily} weakTopic={weak[0]?.topic} syllabusPct={syll} setNotes={notes=>setP(x=>({...x,notes}))} onFocusComplete={()=>addActivity(3)} setExamDate={examDate=>setP(x=>({...x,examDate}))}/>}
    {view==='papers'&&<Papers/>}
    {view==='practice'&&<Practice bank={bank} bookmarks={p.bookmarks} onToggleBookmark={toggleBookmark} onAnswer={(q,selected,ok)=>{setP(x=>{const t=x.topics[q.topic]||{a:0,c:0},count=(x.activity[today]||0)+1;const review=ok?x.review:(x.review.includes(q.id)?x.review:[q.id,...x.review]);void saveQuestionAttempt(q.id,selected,ok,'practice');void saveActivity(today,count,x.daily[today]||{});return{...x,attempts:x.attempts+1,correct:x.correct+(ok?1:0),review,topics:{...x.topics,[q.topic]:{a:t.a+1,c:t.c+(ok?1:0)}},activity:{...x.activity,[today]:count}}})}}/>}
    {view==='mock'&&<Mock bank={bank} onDone={(kind,score,answers)=>setP(x=>{const count=(x.activity[today]||0)+5;void saveMockAttempt(kind,score,answers);void saveActivity(today,count,x.daily[today]||{});return{...x,mocks:[{date:new Date().toISOString(),kind,score},...x.mocks].slice(0,20),activity:{...x.activity,[today]:count}}})}/>} 
    {view==='syllabus'&&<Syllabus done={p.done} onToggle={(id,completed)=>setP(x=>{const done=completed?(x.done.includes(id)?x.done:[...x.done,id]):x.done.filter(v=>v!==id),count=(x.activity[today]||0)+1;void saveSyllabusProgress(id,completed);void saveActivity(today,count,x.daily[today]||{});return{...x,done,activity:{...x.activity,[today]:count}}})}/>} 
    {view==='revision'&&<RevisionLab bank={bank} p={p} toggleBookmark={toggleBookmark} removeReview={id=>setP(x=>{const count=(x.activity[today]||0)+1;void markRevisionReviewed(id);void saveActivity(today,count,x.daily[today]||{});return{...x,review:x.review.filter(v=>v!==id),activity:{...x.activity,[today]:count}}})}/>} 
    {view==='analytics'&&<Analytics bank={bank} p={p} weak={weak} streak={streak} setWeeklyTarget={weeklyTarget=>setP(x=>({...x,weeklyTarget}))}/>}
   </div>
  </main>
 </div>
}
function title(v:View){return({dashboard:'Command Center',planner:'Study Planner',papers:'Previous Paper Library',practice:'Smart Practice',mock:'HAS Mock Exam',syllabus:'Syllabus Tracker',revision:'Revision Lab',analytics:'Performance Analytics'})[v]}
function calcStreak(activity:Record<string,number>){let d=new Date(),n=0;if(!(activity[localKey(d)]>0))d.setDate(d.getDate()-1);for(let i=0;i<365;i++){if(activity[localKey(d)]>0){n++;d.setDate(d.getDate()-1)}else break}return n}

function Login({onOk}:{onOk:()=>void|Promise<void>}){
 const[e,setE]=useState(''),[pw,setPw]=useState(''),[err,setErr]=useState('');
 async function submit(ev:FormEvent){ev.preventDefault();setErr('');const {session,error}=await signInStudyUser(e.trim().toLowerCase(),pw);if(error||!session){setErr('Incorrect email or password.');return}await onOk()}
 return <main className={s.login}><div className={s.loginGlow}/><div className={s.loginNoise}/><section className={s.loginShell}>
  <div className={s.loginIntro}><span className={s.kicker}>HAS PREPARATION · REIMAGINED</span><h1>Your exam prep.<br/><em>One intelligent system.</em></h1><p>Practice, plan, revise, track mistakes and measure consistency without jumping between apps.</p><div className={s.loginStats}><div><b>26</b><span>Years mapped</span></div><div><b>35d</b><span>Study heatmap</span></div><div><b>∞</b><span>Revision cycles</span></div></div></div>
  <form onSubmit={submit} className={s.loginCard}><div className={s.logo}>H</div><small>VISHU STUDY OS</small><h2>Enter command center</h2><p>Your private HAS preparation workspace.</p><label>Email<input type="email" value={e} onChange={x=>setE(x.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" value={pw} onChange={x=>setPw(x.target.value)} placeholder="••••••••••" required/></label>{err&&<b className={s.error}>{err}</b>}<button>Launch workspace <span>→</span></button><em>Supabase secured authentication · local progress cache enabled</em></form>
 </section></main>
}

function Dashboard({p,acc,syll,weak,readiness,streak,setView,setExamDate,setWeeklyTarget}:{p:Progress;acc:number;syll:number;weak:{topic:string;acc:number;n:number}[];readiness:number;streak:number;setView:(v:View)=>void;setExamDate:(x:string)=>void;setWeeklyTarget:(n:number)=>void}){
 const best=p.mocks.length?Math.max(...p.mocks.map(x=>x.score)):0;
 return <>
  <section className={s.heroV4}><div className={s.heroMesh}/><div className={s.heroCopy}><span className={s.kicker}>PERSONAL PREP INTELLIGENCE</span><h2>Study with a system that <em>gets sharper with you.</em></h2><p>Mistakes become revision, activity becomes consistency data, and weak topics automatically influence what you should do next.</p><div className={s.heroButtons}><button onClick={()=>setView('planner')}>Open today’s plan <span>→</span></button><button onClick={()=>setView('revision')}>Review {p.review.length} mistakes</button></div></div><div className={s.readinessStack}><div className={s.donut} style={{'--score':readiness} as any}><div><b>{readiness}%</b><small>READINESS</small></div></div><div className={s.signal}><i/><span><b>{weak[0]?.topic||'Diagnostic pending'}</b><small>{weak[0]?'Priority repair zone':'Start Smart Practice'}</small></span></div></div></section>

  <section className={s.statRail}><article><span>🔥</span><div><small>STUDY STREAK</small><b>{streak} days</b></div></article><article><span>↺</span><div><small>REVISION QUEUE</small><b>{p.review.length} questions</b></div></article><article><span>★</span><div><small>BOOKMARKS</small><b>{p.bookmarks.length} saved</b></div></article><article><span>◉</span><div><small>BEST MOCK</small><b>{p.mocks.length?best+'%':'—'}</b></div></article><article><span>✓</span><div><small>SYLLABUS</small><b>{syll}%</b></div></article></section>

  <section className={s.bentoCommand}>
   <article className={s.nextAction}><div className={s.cardHead}><div><span className={s.micro}>NEXT BEST ACTION</span><h3>{weak[0]?'Repair '+weak[0].topic:'Run your diagnostic set'}</h3></div><span className={s.aiChip}>SMART</span></div><p>{weak[0]?'Your current accuracy here is '+weak[0].acc+'%. Revise the concept, then answer a focused 10-question set before changing topics.':'Answer a few questions so the system can identify where your time is most valuable.'}</p><div className={s.actionSteps}><span><i>1</i>Review concept</span><span><i>2</i>10 MCQs</span><span><i>3</i>Measure again</span></div><button onClick={()=>setView(weak[0]?'revision':'practice')}>Start now →</button></article>
   <ExamCountdown date={p.examDate} setDate={setExamDate}/>
   <WeeklyPulse activity={p.activity} target={p.weeklyTarget} setTarget={setWeeklyTarget}/>
   <ActivityHeatmap activity={p.activity}/>
  </section>

  <section className={s.metrics}><Metric icon="◎" t="Practice accuracy" v={p.attempts?acc+'%':'—'} d={p.attempts+' questions answered'} tone="violet"/><Metric icon="✓" t="Syllabus complete" v={syll+'%'} d="Prelims + Mains" tone="cyan"/><Metric icon="⚡" t="Weakest area" v={weak[0]?.acc+'%'||'—'} d={weak[0]?.topic||'Awaiting diagnostic'} tone="amber"/><Metric icon="▤" t="Paper coverage" v="2000–25" d="Legacy + modern archive" tone="green"/></section>
  <section className={s.grid2}><Panel title="GS intelligence map" badge="PRIORITY"><Priority rows={gsPriority}/></Panel><Panel title="GSAT intelligence map" badge="QUALIFYING"><Priority rows={gsatPriority}/></Panel></section>
 </>
}
function Metric({icon,t,v,d,tone}:{icon:string;t:string;v:string;d:string;tone:string}){return <article className={s.metric+' '+s[tone]}><div className={s.metricIcon}>{icon}</div><div><span>{t}</span><b>{v}</b><small>{d}</small></div><i/></article>}
function Panel({title,badge,children}:{title:string;badge?:string;children:any}){return <section className={s.panel}><div className={s.panelHead}><h3>{title}</h3>{badge&&<span>{badge}</span>}</div>{children}</section>}
function Priority({rows}:{rows:readonly (readonly [string,number])[]}){return <div className={s.priority}>{rows.map((r,i)=><div key={r[0]}><div className={s.rank}>{String(i+1).padStart(2,'0')}</div><div className={s.priorityMain}><span>{r[0]}</span><div><i style={{width:r[1]+'%'}}/></div></div><strong>{r[1]}</strong></div>)}</div>}

function Planner({p,tasks,setTasks,weakTopic,syllabusPct,setNotes,onFocusComplete,setExamDate}:{p:Progress;tasks:DailyTasks;setTasks:(x:DailyTasks)=>void;weakTopic?:string;syllabusPct:number;setNotes:(x:string)=>void;onFocusComplete:()=>void;setExamDate:(x:string)=>void}){
 return <><div className={s.sectionIntro}><div><span className={s.kicker}>TODAY · PLAN · EXECUTE</span><h2>A study day with structure.</h2><p>Finish the right work, not just more work.</p></div><div className={s.datePill}>{new Date().toLocaleDateString('en-IN',{weekday:'short',day:'2-digit',month:'short'})}</div></div>
 <section className={s.plannerGrid}><DailyMission tasks={tasks} setTasks={setTasks} weakTopic={weakTopic}/><FocusTimer onComplete={onFocusComplete}/><ExamCountdown date={p.examDate} setDate={setExamDate}/><QuickNotes value={p.notes} onChange={setNotes}/></section>
 <section className={s.plannerLower}><SevenDayPlan weakTopic={weakTopic} syllabusPct={syllabusPct} reviewCount={p.review.length}/><DataVault payload={p}/></section></>
}

function Papers(){const[filter,setFilter]=useState<'All'|Kind>('All');return <><div className={s.sectionIntro}><div><span className={s.kicker}>ARCHIVE INTELLIGENCE</span><h2>Learn how HAS asks.</h2><p>Use papers to spot recurring themes and question style.</p></div><Tabs items={['All','GS','GSAT']} active={filter} onPick={x=>setFilter(x as any)}/></div><section className={s.papergrid}>{papers.map(p=><article key={p.year}><div className={s.paperTop}><div><small>{p.legacy?'LEGACY PAPER':'MODERN FORMAT'}</small><b>{p.year}</b></div><span>↗</span></div>{filter!=='GSAT'&&<p><span>General Studies</span><Status x={p.gs}/></p>}{filter!=='GS'&&<p><span>GSAT / Aptitude</span><Status x={p.gsat}/></p>}<a href={p.url} target="_blank">Open paper source</a></article>)}</section><section className={s.insight}><div>i</div><p><b>Archive integrity.</b> Unverified early-year papers remain clearly labeled rather than being replaced by guessed files.</p></section></>}
function Status({x}:{x:string}){return <span className={s.status+' '+(x==='Verified'?s.good:x==='N/A'?s.muted:s.warn)}><i/>{x}</span>}

function Practice({bank,bookmarks,onToggleBookmark,onAnswer}:{bank:Q[];bookmarks:string[];onToggleBookmark:(id:string)=>void;onAnswer:(q:Q,selected:number,ok:boolean)=>void}){
 const[kind,setKind]=useState<Kind>('GS'),[idx,setIdx]=useState(0),[pick,setPick]=useState<number|null>(null),[answered,setAnswered]=useState(false);const qs=bank.filter(x=>x.kind===kind),q=qs[idx%qs.length];const choose=(i:number)=>{if(answered)return;setPick(i);setAnswered(true);onAnswer(q,i,i===q.a)};
 return <><div className={s.sectionIntro}><div><span className={s.kicker}>ACTIVE PRACTICE</span><h2>Answer → understand → retain.</h2><p>{qs.length} questions available · wrong answers automatically enter your Revision Lab.</p></div><Tabs items={['GS','GSAT']} active={kind} onPick={x=>{setKind(x as Kind);setIdx(0);setAnswered(false);setPick(null)}}/></div><section className={s.practiceShell}><aside className={s.practiceRail}><span>QUESTION</span><b>{String(idx%qs.length+1).padStart(2,'0')}</b><small>of {qs.length}</small><div/><button onClick={()=>onToggleBookmark(q.id)}>{bookmarks.includes(q.id)?'★':'☆'}</button></aside><section className={s.quiz}><div className={s.qmeta}><span>{q.topic}</span><small>{q.sourceType==='pyq'?'HPAS PYQ · '+q.year:q.year?'PYQ THEME · '+q.year:'SYLLABUS PRACTICE'}</small></div><h2>{q.q}</h2><div className={s.options}>{q.o.map((o,i)=><button key={o} onClick={()=>choose(i)} className={answered?(i===q.a?s.correct:i===pick?s.wrong:''):''}><b>{String.fromCharCode(65+i)}</b><span>{o}</span><i>{answered&&i===q.a?'✓':answered&&i===pick?'×':''}</i></button>)}</div>{answered&&<div className={s.explain+' '+(pick===q.a?s.explainGood:s.explainBad)}><div className={s.explainTitle}><b>{pick===q.a?'Correct — lock it in':'Added to Revision Lab'}</b><span>{pick===q.a?'✓':'↺'}</span></div><p>{q.why}</p><small>EXAM TAKEAWAY</small><p>{q.tip}</p><button onClick={()=>{setIdx(x=>x+1);setPick(null);setAnswered(false)}}>Next question <span>→</span></button></div>}</section></section></>
}

function Mock({bank,onDone}:{bank:Q[];onDone:(k:string,s:number,a:{externalKey:string;selected:number|null;correctOption:number}[])=>void}){const[kind,setKind]=useState<'GS'|'GSAT'|'Mixed'>('Mixed'),[started,setStarted]=useState(false),[set,setSet]=useState<Q[]>([]),[ans,setAns]=useState<Record<string,number>>({}),[result,setResult]=useState<number|null>(null);const start=()=>{const pool=kind==='Mixed'?bank:bank.filter(q=>q.kind===kind);setSet([...pool].sort(()=>Math.random()-.5).slice(0,Math.min(10,pool.length)));setAns({});setResult(null);setStarted(true)};const finish=()=>{const correct=set.filter(q=>ans[q.id]===q.a).length,wrong=set.filter(q=>ans[q.id]!=null&&ans[q.id]!==q.a).length,raw=correct*2-wrong*(2/3),score=Math.max(0,Math.round(raw/(set.length*2)*100));const answers=set.map(q=>({externalKey:q.id,selected:ans[q.id]??null,correctOption:q.a}));setResult(score);onDone(kind,score,answers)};
 if(!started)return <><div className={s.sectionIntro}><div><span className={s.kicker}>EXAM SIMULATOR</span><h2>Practice pressure before exam day.</h2><p>Negative marking included. Build a repeatable test habit.</p></div></div><section className={s.mockSetup}><div className={s.mockVisual}><span>◉</span><b>Exam mode</b><small>+2 correct · −0.67 wrong</small></div><div><span className={s.micro}>PAPER MIX</span><h3>Choose your mock</h3><Tabs items={['GS','GSAT','Mixed']} active={kind} onPick={x=>setKind(x as any)}/><button className={s.primary} onClick={start}>Start mock exam <span>→</span></button></div></section></>;
 return <section className={s.quiz+' '+s.mockQuiz}>{result!==null?<div className={s.result}><div className={s.resultRing}>{result}%</div><span>MOCK COMPLETE</span><h2>{result>=70?'Strong control.':result>=50?'Good base. Keep refining.':'Review weak areas before your next attempt.'}</h2><button onClick={()=>setStarted(false)}>Create another mock</button></div>:<><div className={s.mockhead}><b>{kind} Mock</b><span>{Object.keys(ans).length}/{set.length} answered</span></div>{set.map((q,n)=><div className={s.mockq} key={q.id}><small>QUESTION {String(n+1).padStart(2,'0')}</small><h3>{q.q}</h3>{q.o.map((o,i)=><label key={o} className={ans[q.id]===i?s.selected:''}><input type="radio" name={q.id} checked={ans[q.id]===i} onChange={()=>setAns(a=>({...a,[q.id]:i}))}/><i>{String.fromCharCode(65+i)}</i>{o}</label>)}</div>)}<button className={s.primary} onClick={finish}>Submit exam</button></>}</section>
}

function Syllabus({done,onToggle}:{done:string[];onToggle:(id:string,completed:boolean)=>void}){const[tab,setTab]=useState<'Prelims'|'Mains'>('Prelims'),list=tab==='Prelims'?prelim:mains,complete=Math.round(done.filter(x=>list.some(i=>i[0]===x)).length/list.length*100);return <><div className={s.sectionIntro}><div><span className={s.kicker}>MASTER PLAN</span><h2>Make the syllabus finite.</h2><p>Every completed block reduces uncertainty.</p></div><Tabs items={['Prelims','Mains']} active={tab} onPick={x=>setTab(x as any)}/></div><section className={s.syllabusHero}><div><span>{tab.toUpperCase()} COMPLETION</span><b>{complete}%</b></div><div className={s.longbar}><i style={{width:complete+'%'}}/></div><a href={tab==='Mains'?official.mains:official.home} target="_blank">Official syllabus ↗</a></section><section className={s.checks}>{list.map((x,i)=><label key={x[0]} className={done.includes(x[0])?s.done:''}><input type="checkbox" checked={done.includes(x[0])} onChange={e=>onToggle(x[0],e.target.checked)}/><i>{done.includes(x[0])?'✓':String(i+1).padStart(2,'0')}</i><span><b>{x[1]} <em>{x[3]}</em></b>{x[2]}</span></label>)}</section></>}

function RevisionLab({bank,p,toggleBookmark,removeReview}:{bank:Q[];p:Progress;toggleBookmark:(id:string)=>void;removeReview:(id:string)=>void}){const[tab,setTab]=useState<'Errors'|'Flashcards'|'Saved'>('Errors');return <><div className={s.sectionIntro}><div><span className={s.kicker}>SPACED REVIEW SYSTEM</span><h2>Turn mistakes into marks.</h2><p>Your wrong answers and saved questions become a reusable revision deck.</p></div><Tabs items={['Errors','Flashcards','Saved']} active={tab} onPick={x=>setTab(x as any)}/></div>{tab==='Errors'&&<ReviewQueue bank={bank} ids={p.review} bookmarks={p.bookmarks} onRemove={removeReview} onToggleBookmark={toggleBookmark}/>} {tab==='Flashcards'&&<Flashcards bank={bank} ids={p.bookmarks.length?p.bookmarks:p.review}/>} {tab==='Saved'&&<Bookmarks bank={bank} ids={p.bookmarks} onToggle={toggleBookmark}/>}</>}

function Analytics({bank,p,weak,streak,setWeeklyTarget}:{bank:Q[];p:Progress;weak:{topic:string;acc:number;n:number}[];streak:number;setWeeklyTarget:(n:number)=>void}){const best=p.mocks.length?Math.max(...p.mocks.map(x=>x.score)):0;return <><section className={s.metrics}><Metric icon="🔥" t="Current streak" v={streak+'d'} d="Consistency matters" tone="violet"/><Metric icon="✓" t="Overall accuracy" v={p.attempts?pct(p.attempts,p.correct)+'%':'—'} d="Practice performance" tone="cyan"/><Metric icon="◉" t="Mocks completed" v={String(p.mocks.length)} d="Recent 20 retained" tone="amber"/><Metric icon="↑" t="Best mock" v={p.mocks.length?best+'%':'—'} d="Negative-marking score" tone="green"/></section><section className={s.analyticsGrid}><Panel title="Weak-topic diagnosis" badge="FOCUS">{weak.length?weak.map(x=><div className={s.weak} key={x.topic}><div><span>{x.topic}</span><small>{x.n} attempts</small></div><div className={s.miniBar}><i style={{width:x.acc+'%'}}/></div><b>{x.acc}%</b></div>):<div className={s.empty}>Answer at least two questions in a topic to unlock diagnosis.</div>}</Panel><Panel title="Recent mock trend" badge="HISTORY">{p.mocks.length?p.mocks.slice(0,8).map(x=><div className={s.weak} key={x.date}><div><span>{x.kind}</span><small>{new Date(x.date).toLocaleDateString('en-IN')}</small></div><div className={s.miniBar}><i style={{width:x.score+'%'}}/></div><b>{x.score}%</b></div>):<div className={s.empty}>No submitted mocks yet.</div>}</Panel><WeeklyPulse activity={p.activity} target={p.weeklyTarget} setTarget={setWeeklyTarget}/><MasteryMatrix bank={bank} topics={p.topics}/><ActivityHeatmap activity={p.activity}/></section></>}
function Tabs({items,active,onPick}:{items:string[];active:string;onPick:(x:string)=>void}){return <div className={s.tabs}>{items.map(x=><button className={active===x?s.activeTab:''} onClick={()=>onPick(x)} key={x}>{x}</button>)}</div>}
